// GENERATED by tools/refgen - do not edit by hand.
// Oracle: glam-rs 0.33.8 (f64) on inputs quantized to Q32.32. Sources:
// tools/refgen/specs/rot2.toml and tools/refgen/src/oracles/rot2.rs
// Regenerate: cargo run --manifest-path tools/refgen/Cargo.toml -- gen rot2

use fixed::Fixed;
use glam_core::mat2::Mat2;
use glam_core::vec2::vec2;
use glamx::rot2::{Rot2, Rot2Trait};

fn next_i64(ref d: Span<i64>) -> i64 {
    *d.pop_front().unwrap()
}

fn next_fixed(ref d: Span<i64>) -> Fixed {
    Fixed { raw: next_i64(ref d) }
}

fn next_vec2(ref d: Span<i64>) -> Rot2 {
    let re = next_fixed(ref d);
    let im = next_fixed(ref d);
    Rot2 { re, im }
}

fn check_raw(actual: i64, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    let expected = next_i64(ref d);
    let diff: i128 = actual.into() - expected.into();
    let diff = if diff < 0 {
        -diff
    } else {
        diff
    };
    assert!(diff <= tol, "{name} #{case}: got {actual}, expected {expected} (tol {tol})");
}

fn check_fixed(actual: Fixed, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_raw(actual.raw, ref d, tol, name, case);
}

fn check_bool(actual: bool, ref d: Span<i64>, name: @ByteArray, case: usize) {
    let value = if actual {
        1
    } else {
        0
    };
    check_raw(value, ref d, 0, name, case);
}

fn check_vec2(actual: Rot2, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_fixed(actual.re, ref d, tol, name, case);
    check_fixed(actual.im, ref d, tol, name, case);
}
// rot2::from_cos_sin_unchecked: 13 cases, tolerance 0 ULP - the constructor copies both scalar
// fields exactly.
#[cairofmt::skip]
const FROM_COS_SIN_UNCHECKED_CASES: [i64; 52] = [
    4294967296, 0, 4294967296, 0,
    0, 4294967296, 0, 4294967296,
    -4294967296, 0, -4294967296, 0,
    2576980378, 3435973837, 2576980378, 3435973837,
    1, -1, 1, -1,
    -4294967296, -731324972, -4294967296, -731324972,
    0, -7, 0, -7,
    3715, -1956739532, 3715, -1956739532,
    4095573994, -4294967296, 4095573994, -4294967296,
    -1343575017, -4095825540, -1343575017, -4095825540,
    -4294967296, -4294967296, -4294967296, -4294967296,
    71217587, -3820070528, 71217587, -3820070528,
    -575046267, -2029608317, -575046267, -2029608317,
];

#[test]
fn golden_rot2_from_cos_sin_unchecked() {
    let name: ByteArray = "rot2::from_cos_sin_unchecked";
    let mut d = FROM_COS_SIN_UNCHECKED_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let actual: Rot2 = Rot2Trait::from_cos_sin_unchecked(a0, a1);
        check_vec2(actual, ref d, 0, @name, case);
        case += 1;
    }
}
// rot2::angle_constructors: 14 cases, tolerance 2 ULP - both constructors use the same `sin_cos`,
// whose error is at most 1.02 ULP; oracle quantization adds at most half an ULP.
#[cairofmt::skip]
const ANGLE_CONSTRUCTORS_CASES: [i64; 70] = [
    0, 4294967296, 0, 4294967296, 0,
    6746518852, 0, 4294967296, 0, 4294967296,
    13493037705, -4294967296, 0, -4294967296, 0,
    -3373259426, 3037000500, -3037000500, 3037000500, -3037000500,
    171205034, 4291555479, 171159698, 4291555479, 171159698,
    6442450944, 303813968, 4284208345, 303813968, 4284208345,
    -16792047426, -3089046545, 2984046836, -3089046545, 2984046836,
    4563215877, 2090479453, 3751884823, 2090479453, 3751884823,
    14756944823, -4110336521, -1245743856, -4110336521, -1245743856,
    17179869184, -2807377975, -3250441967, -2807377975, -3250441967,
    546120, 4294967261, 546120, 4294967261, 546120,
    -12884901888, -4251985396, -606105819, -4251985396, -606105819,
    -13, 4294967296, -13, 4294967296, -13,
    -530961, 4294967263, -530961, 4294967263, -530961,
];

#[test]
fn golden_rot2_angle_constructors() {
    let name: ByteArray = "rot2::angle_constructors";
    let mut d = ANGLE_CONSTRUCTORS_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let (r0, r1): (Rot2, Rot2) = (Rot2Trait::new(a0), Rot2Trait::from_angle(a0));
        check_vec2(r0, ref d, 2, @name, case);
        check_vec2(r1, ref d, 2, @name, case);
        case += 1;
    }
}
// rot2::angle: 14 cases, tolerance 4 ULP - `atan2` is accurate to 3.22 ULP and the f64 result is
// rounded to nearest.
#[cairofmt::skip]
const ANGLE_CASES: [i64; 42] = [
    4294967296, 0, 0,
    0, 4294967296, 6746518852,
    -4294967296, 0, 13493037705,
    0, -4294967296, -6746518852,
    4294967296, 6574, 6574,
    -4279897230, 359477087, 13133139585,
    -2849910413, -3213215634, -9862729267,
    2083115725, -3755978295, -4571640901,
    2809292033, 3248787827, 3684301697,
    3037000500, -3037000500, -3373259426,
    -325321496, 4282628865, 7072152231,
    -1745498084, 3924280891, 8544033556,
    -2353417350, -3592794296, -9237208323,
    -4294802383, -37637311, -13455399912,
];

#[test]
fn golden_rot2_angle() {
    let name: ByteArray = "rot2::angle";
    let mut d = ANGLE_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let actual: Fixed = a0.angle();
        check_fixed(actual, ref d, 4, @name, case);
        case += 1;
    }
}
// rot2::accessors_inverse: 8 cases, tolerance 0 ULP - the accessors copy fields and inverse only
// negates the imaginary field.
#[cairofmt::skip]
const ACCESSORS_INVERSE_CASES: [i64; 48] = [
    -4294967296, 558, -4294967296, 558, -4294967296, -558,
    3854830839, 1893943843, 3854830839, 1893943843, 3854830839, -1893943843,
    2043839565, 3777494395, 2043839565, 3777494395, 2043839565, -3777494395,
    -4131413162, -1173954581, -4131413162, -1173954581, -4131413162, 1173954581,
    -1653469162, 3963935393, -1653469162, 3963935393, -1653469162, -3963935393,
    -4244785473, 654629941, -4244785473, 654629941, -4244785473, -654629941,
    -517720160, 4263649834, -517720160, 4263649834, -517720160, -4263649834,
    355795911, -4280204825, 355795911, -4280204825, 355795911, 4280204825,
];

#[test]
fn golden_rot2_accessors_inverse() {
    let name: ByteArray = "rot2::accessors_inverse";
    let mut d = ACCESSORS_INVERSE_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Rot2) = (a0.cos(), a0.sin(), a0.inverse());
        check_fixed(r0, ref d, 0, @name, case);
        check_fixed(r1, ref d, 0, @name, case);
        check_vec2(r2, ref d, 0, @name, case);
        case += 1;
    }
}
// rot2::mul: 15 cases, tolerance 1 ULP - each component is one exact two-product Q64.64 sum
// floored once, versus round-to-nearest quantization of the f64 oracle.
#[cairofmt::skip]
const MUL_CASES: [i64; 90] = [
    4294967296, 0, 4294967296, 0, 4294967296, 0,
    0, 4294967296, 0, 4294967296, -4294967296, 0,
    2576980378, 3435973837, 3435973837, -2576980378, 4123168605, 1202590843,
    -2796502736, 3259803141, 0, 4294967296, -3259803141, -2796502736,
    -4294967296, -13097, -4294967296, 0, 4294967296, 13097,
    3524815971, -2454061214, -217351960, -4289464092, -2629294320, -3396108868,
    2408809000, 3555894160, -1, 4294967296, -3555894161, 2408808999,
    -3238845439, -2820748889, 55318, -4294967296, -2820790604, 3238809109,
    -188, -4294967296, -2956276981, -3115633240, -3115633111, 2956277117,
    3391906810, -2634712937, 1569367083, -3997978368, -1213135764, -4120078359,
    65393, -4294967296, 4294967296, 48, 65441, -4294967296,
    -3226269180, -2835124557, 4038143673, 1462921649, -2067669617, -3764503477,
    0, 4294967296, 285529644, -4285465774, 4285465774, 285529644,
    -1751660, 4294966939, 1067451666, -4160203242, 4159767547, 1069148275,
    -3037000500, -3037000500, -4294967296, -2824, 3036998503, 3037002497,
];

#[test]
fn golden_rot2_mul() {
    let name: ByteArray = "rot2::mul";
    let mut d = MUL_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let actual: Rot2 = a0 * a1;
        check_vec2(actual, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::transform_vector: 13 cases, tolerance 1 ULP - each output is one exact two-product Q64.64
// sum floored once.
#[cairofmt::skip]
const TRANSFORM_VECTOR_CASES: [i64; 78] = [
    4294967296, 0, 4294967296, 8589934592, 4294967296, 8589934592,
    0, 4294967296, 4294967296, 0, 0, 4294967296,
    2576980378, 3435973837, -12884901888, 17179869184, -21474836482, 1,
    5109, 4294967296, 2147483648, -21237707303, 21237709858, 2147458385,
    -4292363854, -149521311, -22354934857, 33533721334, 23508798404, -32735148952,
    3080065306, -2993316185, 36296910, -32360889077, -22527430249, -23232377098,
    3063315190, 3010455799, -23618551705, 9837212078, -23740707047, -9538634857,
    781253161, 4223314761, -481939, 0, -87665, -473899,
    3403010993, -2620354986, 8589934592, 4295038569, 9426420456, -1837642508,
    -4294966830, 2000012, -22345840982, -8775075, 22345842644, -1630581,
    0, 4294967296, 31444330786, 4294967296, -4294967296, 31444330786,
    -4136534895, 1155778152, 78, -6417428082, 1726933486, 6180702543,
    0, 4294967296, 17179869184, -17179869184, 17179869184, 17179869184,
];

#[test]
fn golden_rot2_transform_vector() {
    let name: ByteArray = "rot2::transform_vector";
    let mut d = TRANSFORM_VECTOR_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = (next_fixed(ref d), next_fixed(ref d));
        let (r0, r1): (Fixed, Fixed) = {
            let (x, y) = a1;
            let v = vec2(x, y);
            let r = a0.transform_vector(v);
            (r.x, r.y)
        };
        check_fixed(r0, ref d, 1, @name, case);
        check_fixed(r1, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::inverse_transform_vector: 13 cases, tolerance 1 ULP - each output is one exact
// two-product Q64.64 sum floored once.
#[cairofmt::skip]
const INVERSE_TRANSFORM_VECTOR_CASES: [i64; 78] = [
    4294967296, 0, 4294967296, 8589934592, 4294967296, 8589934592,
    0, 4294967296, 4294967296, 0, 0, -4294967296,
    2576980378, 3435973837, -12884901888, 17179869184, 6012954214, 20615843023,
    0, 4294967296, -11710807, -153715280, -153715280, 11710807,
    -7, 4294967296, 25769803776, -30064771072, -30064771114, -25769803727,
    4141623962, -1137407155, 7467, 32963117491, -8729392374, 31786236390,
    -3209617774, 2853961776, 25769803776, 22045977329, -4608380520, -33598671582,
    0, -4294967296, 1915483367, -24450876448, 24450876448, 1915483367,
    4294967146, 1135159, 27354351671, 25769803776, 27361161670, 25762573126,
    4162046428, 1060242239, 13237482107, -27917287424, 5936233279, -30321065353,
    -1546038487, -4007057408, -30064771072, 10712208529, 828145686, -31905423456,
    -32, -4294967296, 13033383410, -404, 307, 13033383410,
    4294967296, 0, 18150732109, -21474836480, 18150732109, -21474836480,
];

#[test]
fn golden_rot2_inverse_transform_vector() {
    let name: ByteArray = "rot2::inverse_transform_vector";
    let mut d = INVERSE_TRANSFORM_VECTOR_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = (next_fixed(ref d), next_fixed(ref d));
        let (r0, r1): (Fixed, Fixed) = {
            let (x, y) = a1;
            let v = vec2(x, y);
            let r = a0.inverse_transform_vector(v);
            (r.x, r.y)
        };
        check_fixed(r0, ref d, 1, @name, case);
        check_fixed(r1, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::mul_vec2_alias: 6 cases, tolerance 1 ULP - the named heterogeneous product is the same
// fused transform as upstream's operator.
#[cairofmt::skip]
const MUL_VEC2_ALIAS_CASES: [i64; 48] = [
    324291205, -4282707005, -16256302631, 8448108600,
        7196561878, 16847771702, 7196561878, 16847771702,
    -4294610105, -55390594, -15327769553, -6641574570,
        15240840905, 6838698760, 15240840905, 6838698760,
    1378451016, 4067753295, -180882, -12151787924,
        11508871343, -3900234633, 11508871343, -3900234633,
    0, -4294967296, -88, -31904995531, -31904995531, 88, -31904995531, 88,
    2669578747, -3364534646, -34359738368, 27803986107,
        424088737, 44198115487, 424088737, 44198115487,
    -987979710, -4179789488, -17465548344, -5119993800,
        -965057145, 18174938243, -965057145, 18174938243,
];

#[test]
fn golden_rot2_mul_vec2_alias() {
    let name: ByteArray = "rot2::mul_vec2_alias";
    let mut d = MUL_VEC2_ALIAS_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = (next_fixed(ref d), next_fixed(ref d));
        let (r0, r1, r2, r3): (Fixed, Fixed, Fixed, Fixed) = {
            let (x, y) = a1;
            let v = vec2(x, y);
            let a = a0.mul_vec2(v);
            let b = a0.transform_vector(v);
            (a.x, a.y, b.x, b.y)
        };
        check_fixed(r0, ref d, 1, @name, case);
        check_fixed(r1, ref d, 1, @name, case);
        check_fixed(r2, ref d, 1, @name, case);
        check_fixed(r3, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::to_mat: 8 cases, tolerance 0 ULP - matrix conversion copies two fields and negates the
// sine exactly.
#[cairofmt::skip]
const TO_MAT_CASES: [i64; 48] = [
    3022668813, -3051264872, 3022668813, -3051264872, 3051264872, 3022668813,
    -1, -4294967296, -1, -4294967296, 4294967296, -1,
    -2887191456, 3179759357, -2887191456, 3179759357, -3179759357, -2887191456,
    4294841387, -32886678, 4294841387, -32886678, 32886678, 4294841387,
    -3037000500, 3037000500, -3037000500, 3037000500, -3037000500, -3037000500,
    0, 4294967296, 0, 4294967296, -4294967296, 0,
    -204615768, -4290090496, -204615768, -4290090496, 4290090496, -204615768,
    -2149013194, -3718667283, -2149013194, -3718667283, 3718667283, -2149013194,
];

#[test]
fn golden_rot2_to_mat() {
    let name: ByteArray = "rot2::to_mat";
    let mut d = TO_MAT_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let (r0, r1, r2, r3): (Fixed, Fixed, Fixed, Fixed) = {
            let m = a0.to_mat();
            (m.x_axis.x, m.x_axis.y, m.y_axis.x, m.y_axis.y)
        };
        check_fixed(r0, ref d, 0, @name, case);
        check_fixed(r1, ref d, 0, @name, case);
        check_fixed(r2, ref d, 0, @name, case);
        check_fixed(r3, ref d, 0, @name, case);
        case += 1;
    }
}
// rot2::from_mat_pair: 13 cases, tolerance 3 ULP - unchecked extraction is exact; normalization
// of a length-at-least-one column has at most 1 ULP from the floored length, one rounded division
// and oracle quantization.
#[cairofmt::skip]
const FROM_MAT_PAIR_CASES: [i64; 78] = [
    4294967296, 0, 4294967296, 0, 4294967296, 0,
    12884901888, 17179869184, 2576980378, 3435973837, 12884901888, 17179869184,
    -8589934592, 4294967296, -3841535534, 1920767767, -8589934592, 4294967296,
    15032385536, 9015539308, 3683324731, 2209041194, 15032385536, 9015539308,
    44, 27917287424, 7, 4294967296, 44, 27917287424,
    -25769803776, 687226491, -4293440870, 114497042, -25769803776, 687226491,
    0, -19968665425, 0, -4294967296, 0, -19968665425,
    -30064771072, 26256180787, -3234983370, 2825177281, -30064771072, 26256180787,
    29058268185, 750, 4294967296, 111, 29058268185, 750,
    29030599602, -1, 4294967296, 0, 29030599602, -1,
    32315762054, 0, 4294967296, 0, 32315762054, 0,
    -2147483648, -34359738368, -267912699, -4286603184, -2147483648, -34359738368,
    29, -33497915605, 4, -4294967296, 29, -33497915605,
];

#[test]
fn golden_rot2_from_mat_pair() {
    let name: ByteArray = "rot2::from_mat_pair";
    let mut d = FROM_MAT_PAIR_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let (r0, r1): (Rot2, Rot2) = {
            let m = Mat2 { x_axis: vec2(a0.re, a0.im), y_axis: vec2(-a0.im, a0.re) };
            (Rot2Trait::from_mat(m), Rot2Trait::from_mat_unchecked(m))
        };
        check_vec2(r0, ref d, 3, @name, case);
        check_vec2(r1, ref d, 3, @name, case);
        case += 1;
    }
}
// rot2::normalize_pair: 13 cases, tolerance 3 ULP - the floored length contributes at most 1 ULP
// relative error for length >= 1, the shared division rounds once and oracle quantization adds
// half an ULP.
#[cairofmt::skip]
const NORMALIZE_PAIR_CASES: [i64; 78] = [
    4294967296, 0, 4294967296, 0, 4294967296, 0,
    12884901888, 17179869184, 2576980378, 3435973837, 2576980378, 3435973837,
    -8589934592, 4294967296, -3841535534, 1920767767, -3841535534, 1920767767,
    -356611542, -25769803776, -59429567, -4294556112, -59429567, -4294556112,
    7672250903, -11215677754, 2424947191, -3544908348, 2424947191, -3544908348,
    -361981, -19327352832, -80440, -4294967295, -80440, -4294967295,
    16141306281, 25401733060, 2303482006, 3625012375, 2303482006, 3625012375,
    11322291172, -3126092502, 4140063405, -1143074398, 4140063405, -1143074398,
    15500675010, 31482051187, 1897197648, 3853230483, 1897197648, 3853230483,
    1244080385, 19012278106, 280444124, 4285801578, 280444124, 4285801578,
    -34359738368, 0, -4294967296, 0, -4294967296, 0,
    -989, 28169508268, -151, 4294967296, -151, 4294967296,
    -28234733647, -30064771072, -2940220007, -3130790696, -2940220007, -3130790696,
];

#[test]
fn golden_rot2_normalize_pair() {
    let name: ByteArray = "rot2::normalize_pair";
    let mut d = NORMALIZE_PAIR_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let (r0, r1): (Rot2, Rot2) = {
            let mut q = a0;
            q.normalize_mut();
            (a0.normalize(), q)
        };
        check_vec2(r0, ref d, 3, @name, case);
        check_vec2(r1, ref d, 3, @name, case);
        case += 1;
    }
}
// rot2::length_pair: 13 cases, tolerance 1 ULP - the integer square root and fused sum of squares
// each floor the exact result once.
#[cairofmt::skip]
const LENGTH_PAIR_CASES: [i64; 52] = [
    0, 0, 0, 0,
    12884901888, 17179869184, 21474836480, 107374182400,
    1, -1, 1, 0,
    -3, -12884901888, 12884901888, 38654705664,
    21723837830, 62, 21723837830, 109878631789,
    6896623153, 7303857362, 10045384178, 23494880479,
    -8008295470, 0, 8008295470, 14932080250,
    -12884901888, 29091728356, 31817437914, 235705952021,
    24359023775, -25769803776, 35460468496, 292771688179,
    -29527402727, -26719470442, 39822074437, 369222278824,
    -109659474, -16269341124, 16269710686, 61631082978,
    17733447546, 4294967296, 18246147701, 77514421647,
    -20343222291, -30064771072, 36300649482, 306809589451,
];

#[test]
fn golden_rot2_length_pair() {
    let name: ByteArray = "rot2::length_pair";
    let mut d = LENGTH_PAIR_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let (r0, r1): (Fixed, Fixed) = (a0.length(), a0.length_squared());
        check_fixed(r0, ref d, 1, @name, case);
        check_fixed(r1, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::dot: 12 cases, tolerance 1 ULP - one exact two-product Q64.64 sum is floored once.
#[cairofmt::skip]
const DOT_CASES: [i64; 60] = [
    4294967296, 0, 0, 4294967296, 0,
    12884901888, 17179869184, 17179869184, -12884901888, 0,
    -25769803776, 3511128827, -3249898108, 2175610870, 21277947020,
    17179869184, 800, 2092787829, -19327352832, 8371147716,
    14693, -19932510582, -4294967296, 19512246906, -90554387085,
    8344, 270101561, 588, 1514485, 95243,
    -4294967296, 0, 16168, -19327352832, -16168,
    21770585279, -2226142140, -5941159358, 11473955536, -36062014380,
    -1719924614, -4294967296, 32158252531, 25769803776, -38647613142,
    -23228118303, 0, 11692253649, -10988054994, -63234253551,
    17754962682, -21172985879, 21474836480, 28176670675, -50128281586,
    -1, 10076440318, -850, 13893424598, 32595420204,
];

#[test]
fn golden_rot2_dot() {
    let name: ByteArray = "rot2::dot";
    let mut d = DOT_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let actual: Fixed = a0.dot(a1);
        check_fixed(actual, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::is_normalized: 15 cases, tolerance 0 ULP - exact comparison; random cases are far from
// both thresholds (1024 raw ULP here, 2e-4 upstream), edge cases at the Q32.32 band are in the
// unit tests.
#[cairofmt::skip]
const IS_NORMALIZED_CASES: [i64; 45] = [
    4294967296, 0, 1,
    0, -4294967296, 1,
    2576980378, 3435973837, 1,
    2147483648, 2147483648, 0,
    0, 0, 0,
    -4294967296, 951190876, 0,
    -1422073081, 2952039725, 0,
    -4294967296, -3495665134, 0,
    -124628340, 71500044, 0,
    0, 869795430, 0,
    2903693000, -610262601, 0,
    0, -2899974014, 0,
    0, 0, 0,
    -645551, -4294967296, 1,
    -4193379434, -313, 0,
];

#[test]
fn golden_rot2_is_normalized() {
    let name: ByteArray = "rot2::is_normalized";
    let mut d = IS_NORMALIZED_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let actual: bool = a0.is_normalized();
        check_bool(actual, ref d, @name, case);
        case += 1;
    }
}
// rot2::lerp: 20 cases, tolerance 1 ULP - each component is `re + (rhs.re - re) * s` as upstream,
// evaluated exactly and floored once (`Fixed::lerp`), versus round-to-nearest quantization of the
// f64 oracle: |diff| <= 1, and exact at `s = 0`, `s = 1` and on dyadic midpoints. Not normalized:
// the midpoint of antipodes is `(0, 0)`.
#[cairofmt::skip]
const LERP_CASES: [i64; 140] = [
    4294967296, 0, 0, 4294967296, 0, 4294967296, 0,
    4294967296, 0, 0, 4294967296, 2147483648, 2147483648, 2147483648,
    4294967296, 0, 0, 4294967296, 4294967296, 0, 4294967296,
    4294967296, 0, -4294967296, 0, 2147483648, 0, 0,
    0, 4294967296, 0, -4294967296, 2147483648, 0, 0,
    2576980378, 3435973837, -2576980378, -3435973837, 2147483648, 0, 0,
    2576980378, 3435973837, 3435973837, -2576980378, 1073741824, 2791728743, 1932735283,
    4294967296, 0, 0, 4294967296, 8589934592, -4294967296, 8589934592,
    -2911525532, -3157493175, -4294967296, 13, 1648974115, -3442672687, -1945231433,
    -2990727860, -3082578619, 1502660314, -4023525327, 0, -2990727860, -3082578619,
    -644878029, -4246277947, -869164, -4294967208, 308077293, -598683380, -4249770420,
    0, -4294967296, 4294951356, 11701264, 4083361554, 4083346399, -200480979,
    -3522783985, 2456977222, 0, -4294967296, 125, -3522783882, 2456977025,
    6, 4294967296, -3798603212, 2004334730, 0, 6, 4294967296,
    -2704831033, -3336260355, -1673212281, 3955642140, 211474, -2704780239, -3335901319,
    -4269666063, -465505943, -3407023794, -2615135358, 2254955634, -3816759228, -1594110337,
    -56117610, -4294600667, 0, 4294967296, 26136, -56117269, -4294548397,
    3448515702, -2560172557, 1679043660, -3953170431, 133, 3448515647, -2560172600,
    3167637281, -2900485844, 1639285362, 3969822109, 3032250782, 2088619449, 1949957763,
    -2813629779, -3245031824, 4271943606, -444119240, 1599020373, -175664128, -2202249429,
];

#[test]
fn golden_rot2_lerp() {
    let name: ByteArray = "rot2::lerp";
    let mut d = LERP_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let a2 = next_fixed(ref d);
        let actual: Rot2 = a0.lerp(a1, a2);
        check_vec2(actual, ref d, 1, @name, case);
        case += 1;
    }
}
// rot2::slerp: 15 cases, tolerance 12 ULP - one `atan2` (3.22 ULP), one angle product, one
// `sin_cos` (1.02 ULP) and one fused complex product, with conditioning bounded for unit inputs.
#[cairofmt::skip]
const SLERP_CASES: [i64; 105] = [
    4294967296, 0, 0, 4294967296, 0, 4294967296, 0,
    4294967296, 0, 0, 4294967296, 2147483648, 3037000500, 3037000500,
    4294967296, 0, 0, 4294967296, 4294967296, 0, 4294967296,
    -156026921, -4292132299, -4294967296, 2350, 87903758, -290723683, -4285116546,
    -3734961491, -2120567549, -3037000500, -3037000500, 3078, -3734961082, -2120568269,
    -1258809227, -4106354028, 4283464768, -314123636, 1170867, -1256799611, -4106969541,
    -848400215, 4210339790, -4294967296, -8, 5248936, -855458430, 4208911373,
    1118100281, -4146877842, 4294910689, 22050941, 0, 1118100281, -4146877842,
    -3065788437, -3007937056, 0, -4294967296, 3, -3065788435, -3007937058,
    3719286431, -2147941460, -2, -4294967296, 3286843992, 1044985411, -4165903211,
    -4294902704, 23554918, 4294966963, 1690265, 1003420462, -3177275782, 2889924338,
    -4294967296, 0, 0, -4294967296, 0, -4294967296, 0,
    -3990530437, 1588209969, 0, 4294967296, 0, -3990530437, 1588209969,
    4046809593, 1438775936, -440716792, 4272295961, 0, 4046809593, 1438775936,
    -100551107, -4293790115, -1842736848, 3879570206, 0, -100551107, -4293790115,
];

#[test]
fn golden_rot2_slerp() {
    let name: ByteArray = "rot2::slerp";
    let mut d = SLERP_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let a2 = next_fixed(ref d);
        let actual: Rot2 = a0.slerp(a1, a2);
        check_vec2(actual, ref d, 12, @name, case);
        case += 1;
    }
}
// rot2::angle_between: 13 cases, tolerance 6 ULP - the relative rotation floors each component
// once before an `atan2` accurate to 3.22 ULP.
#[cairofmt::skip]
const ANGLE_BETWEEN_CASES: [i64; 65] = [
    4294967296, 0, 0, 4294967296, 6746518852,
    0, 4294967296, 4294967296, 0, -6746518852,
    4294967296, 0, -4294967296, 0, 13493037705,
    0, -4294967296, -4095390569, 1294032519, -8060975015,
    0, -4294967296, 3125947747, -2945368356, 3500967156,
    4028604509, -1488989518, -719, -4294967296, -5225964501,
    -2608209279, 3412328887, 3286204641, 2765430009, -6544942213,
    -4294967296, -1432, 4294967296, 0, 13493036273,
    -4276017795, 403008545, -4294967296, -2, 403602290,
    0, -4294967296, -3528343164, -2448987258, -4140554261,
    3204617158, -2859575659, 2966135219, -3106249497, -343197139,
    -3745322, 4294965663, 4235866262, 710057098, -6036932122,
    -3037000500, -3037000500, 0, -4294967296, 3373259426,
];

#[test]
fn golden_rot2_angle_between() {
    let name: ByteArray = "rot2::angle_between";
    let mut d = ANGLE_BETWEEN_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let actual: Fixed = a0.angle_between(a1);
        check_fixed(actual, ref d, 6, @name, case);
        case += 1;
    }
}
// rot2::rotate_towards: 13 cases, tolerance 16 ULP - the non-target branch is `slerp(max_angle /
// angle)` with one rounded division added to the slerp error; branch-boundary cases are skipped.
#[cairofmt::skip]
const ROTATE_TOWARDS_CASES: [i64; 91] = [
    4294967296, 0, 0, 4294967296, 0, 4294967296, 0,
    4294967296, 0, 0, 4294967296, 2147483648, 3769188403, 2059117009,
    4294967296, 0, 0, 4294967296, 4294967296, 2320580734, 3614090360,
    -2497684569, -3494040049, 0, 4294967296, 1862799366, -798066573, -4220169880,
    -3551560255, -2415194367, 2732405568, 3313714515, 1096561923, -2826480050, -3233845173,
    26, -4294967296, 3181042813, -2885777312, -2147483648, -2059116986, -3769188415,
    -4294966925, 1784087, 0, -4294967296, 114677759, -4293483670, -112880673,
    -4294967296, -748, 4294967296, 0, 3532921482, -2922029622, -3147774922,
    4294967296, -478, -4294967296, 0, -4250079918, 2358224339, -3589640935,
    -358, 4294967296, -4294967296, 0, -4294967296, 3614090167, 2320581035,
    0, -4294967296, -4294967296, 0, -1184452300, -1169495794, -4132677541,
    741401588, -4230492614, -2, 4294967296, 23140883, 764184216, -4226436626,
    0, 4294967296, -4294964793, -4637260, 0, 0, 4294967296,
];

#[test]
fn golden_rot2_rotate_towards() {
    let name: ByteArray = "rot2::rotate_towards";
    let mut d = ROTATE_TOWARDS_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_vec2(ref d);
        let a1 = next_vec2(ref d);
        let a2 = next_fixed(ref d);
        let actual: Rot2 = a0.rotate_towards(a1, a2);
        check_vec2(actual, ref d, 16, @name, case);
        case += 1;
    }
}
// rot2::from_rotation_arc: 13 cases, tolerance 1 ULP - the dot and determinant are each one exact
// two-product Q64.64 sum floored once.
#[cairofmt::skip]
const FROM_ROTATION_ARC_CASES: [i64; 78] = [
    4294967296, 0, 0, 4294967296, 0, 4294967296,
    0, 4294967296, 4294967296, 0, 0, -4294967296,
    4294967296, 0, -4294967296, 0, -4294967296, 0,
    1650701192, -581730024, -4294967296, -1859036911, -1398904726, -1296220783,
    -2147483648, 269635901, -2556618316, 65, 1278309162, 160503188,
    2171863659, -9905, -4294967296, -2147483648, -2171858707, -1085941735,
    513566064, 0, 0, 3263361144, 0, 390212875,
    -3949552603, -2147483648, -1510359360, -2147483648, 2462633364, 1219596622,
    4267343247, 4229367634, 2147483648, -3783568060, -1592107688, -5873917007,
    3360899490, 3702098305, 4257566642, 0, 3331632716, -3669860365,
    -67013, 0, -928523643, 3283320797, 14487, -51229,
    0, -1602690, -1181326580, -1155017769, 431001, -440818,
    -3038114960, 0, 409631325, -1546046573, -289759379, 1093621185,
];

#[test]
fn golden_rot2_from_rotation_arc() {
    let name: ByteArray = "rot2::from_rotation_arc";
    let mut d = FROM_ROTATION_ARC_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = (next_fixed(ref d), next_fixed(ref d));
        let a1 = (next_fixed(ref d), next_fixed(ref d));
        let actual: Rot2 = {
            let (fx, fy) = a0;
            let (tx, ty) = a1;
            Rot2Trait::from_rotation_arc(vec2(fx, fy), vec2(tx, ty))
        };
        check_vec2(actual, ref d, 1, @name, case);
        case += 1;
    }
}
