//! Tests of `glamx::sdp`: layout and constructors, exact cases of the world-inertia kernel (axis
//! permutations), agreement with the full `Mat3` / `Mat2` products, inversion round trips in raw
//! ULPs, seeded fuzz properties, and one test per panic path.
//!
//! The reference results themselves are checked by `golden_sdp.cairo` (generated by
//! `tools/refgen`: exact integer oracles and glam `DMat3` / `DMat2` in f64).

use fixed::fixed::{FRAC_1_SQRT_2, Fixed, FixedTrait};
use fixed::wide::mul_sub;
use glam_core::mat2::{Mat2, Mat2Trait};
use glam_core::mat3::{Mat3, Mat3Trait};
use glam_core::quat::{Quat, QuatTrait};
use glam_core::vec2::Vec2;
use glam_core::vec3::{Vec3, Vec3Trait};
use glamx::sdp::{SdpMatrix2, SdpMatrix2Trait, SdpMatrix3, SdpMatrix3Trait};

const ONE: i64 = 0x100000000;

/// A `Fixed` from its raw Q32.32 value.
fn f(raw: i64) -> Fixed {
    FixedTrait::from_raw(raw)
}

/// A `Fixed` from an integer.
fn n(v: i64) -> Fixed {
    f(v * ONE)
}

fn v3(x: i64, y: i64, z: i64) -> Vec3 {
    Vec3 { x: n(x), y: n(y), z: n(z) }
}

/// A matrix from its 9 integer entries in column-major order.
fn m3(c: [i64; 9]) -> Mat3 {
    let [a, b, c, d, e, g, h, i, j] = c;
    Mat3 { x_axis: v3(a, b, c), y_axis: v3(d, e, g), z_axis: v3(h, i, j) }
}

/// `S = [[2, 1, 0.5], [1, 3, -1], [0.5, -1, 4]]`: symmetric positive-definite (det 17.25).
fn s_ref() -> SdpMatrix3 {
    SdpMatrix3Trait::new(n(2), n(1), f(ONE / 2), n(3), n(-1), n(4))
}

/// `true` if every raw entry of `a` and `b` differs by at most `ulp`.
fn near3(a: SdpMatrix3, b: SdpMatrix3, ulp: i64) -> bool {
    a.into_matrix().abs_diff_eq(b.into_matrix(), f(ulp))
}

// ------------------------------------------------------------------------------------------------
// Fuzz input helpers.

/// `lo + (v mod span)` as a raw value, `span > 0`.
fn in_range(v: i64, lo: i64, span: i64) -> Fixed {
    f(lo + ((v % span) + span) % span)
}

/// The `k`-th fuzzed matrix element, |value| <= 8: every kernel below stays far from overflow.
fn cell(v: i64, k: i64) -> Fixed {
    f((v / (k + 1) + k * 2654435761) % 0x800000000)
}

fn fuzz_mat(a: i64, b: i64, c: i64, d: i64) -> Mat3 {
    Mat3Trait::from_cols_array(
        [
            cell(a, 0), cell(b, 1), cell(c, 2), cell(d, 3), cell(a, 4), cell(b, 5), cell(c, 6),
            cell(d, 7), cell(a, 8),
        ],
    )
}

fn fuzz_sdp(a: i64, b: i64, c: i64, d: i64) -> SdpMatrix3 {
    SdpMatrix3Trait::new(
        cell(b, 9), cell(c, 10), cell(d, 11), cell(a, 12), cell(b, 13), cell(c, 14),
    )
}

/// A unit quaternion: a fuzzed `Vec4` with `w >= 1/4`, normalized.
fn fuzz_quat(a: i64, b: i64, c: i64, d: i64) -> Quat {
    QuatTrait::from_xyzw(
        in_range(a, -ONE, 2 * ONE),
        in_range(b, -ONE, 2 * ONE),
        in_range(c, -ONE, 2 * ONE),
        in_range(d, ONE / 4, ONE),
    )
        .normalize()
}

/// `R diag(e) R^T` with a fuzzed rotation and eigenvalues `e` in `[1, 1 + span)` (raw `span`).
fn fuzz_spd(a: i64, b: i64, c: i64, d: i64, span: i64) -> SdpMatrix3 {
    let e = Vec3 {
        x: in_range(a, ONE, span), y: in_range(b, ONE, span), z: in_range(c, ONE, span),
    };
    SdpMatrix3Trait::from_rotated_diagonal(fuzz_quat(a, b, c, d), e)
}

// ------------------------------------------------------------------------------------------------
// Layout and constructors.

#[test]
fn test_constructors_and_layout() {
    let s = s_ref();
    assert_eq!(s.m11, n(2));
    assert_eq!(s.m12, n(1));
    assert_eq!(s.m13, f(ONE / 2));
    assert_eq!(s.m22, n(3));
    assert_eq!(s.m23, n(-1));
    assert_eq!(s.m33, n(4));
    let m = s.into_matrix();
    assert_eq!(m.transpose(), m);
    assert_eq!(m.x_axis, Vec3 { x: n(2), y: n(1), z: f(ONE / 2) });
    assert_eq!(m.z_axis, Vec3 { x: f(ONE / 2), y: n(-1), z: n(4) });
    assert_eq!(SdpMatrix3Trait::from_sdp_matrix(m), s);
    // `from_sdp_matrix` reads the upper triangle only
    let skew = m3([2, 100, 200, 1, 3, 300, 7, -1, 4]);
    let upper = SdpMatrix3Trait::from_sdp_matrix(skew);
    assert_eq!(upper, SdpMatrix3Trait::new(n(2), n(1), n(7), n(3), n(-1), n(4)));

    assert_eq!(SdpMatrix3Trait::zero().into_matrix(), Mat3Trait::ZERO);
    assert_eq!(SdpMatrix3Trait::identity().into_matrix(), Mat3Trait::IDENTITY);
    assert_eq!(
        SdpMatrix3Trait::diagonal(n(5)).into_matrix(), Mat3Trait::from_diagonal(v3(5, 5, 5)),
    );
    let d: SdpMatrix3 = Default::default();
    assert_eq!(d, SdpMatrix3Trait::zero());
    assert!(SdpMatrix3Trait::zero().is_zero());
    assert!(!SdpMatrix3Trait::identity().is_zero());
    // `is_zero` looks at every component
    let mut k: u32 = 0;
    while k != 6 {
        let raw = match k {
            0 => SdpMatrix3Trait::new(f(1), n(0), n(0), n(0), n(0), n(0)),
            1 => SdpMatrix3Trait::new(n(0), f(1), n(0), n(0), n(0), n(0)),
            2 => SdpMatrix3Trait::new(n(0), n(0), f(-1), n(0), n(0), n(0)),
            3 => SdpMatrix3Trait::new(n(0), n(0), n(0), f(1), n(0), n(0)),
            4 => SdpMatrix3Trait::new(n(0), n(0), n(0), n(0), f(-1), n(0)),
            _ => SdpMatrix3Trait::new(n(0), n(0), n(0), n(0), n(0), f(1)),
        };
        assert!(!raw.is_zero(), "is_zero #{}", k);
        k += 1;
    }

    let s2 = SdpMatrix2Trait::new(n(2), n(-1), n(3));
    let m2 = s2.into_matrix();
    assert_eq!(m2.transpose(), m2);
    assert_eq!(m2.y_axis, Vec2 { x: n(-1), y: n(3) });
    assert_eq!(SdpMatrix2Trait::from_sdp_matrix(m2), s2);
    let skew2 = Mat2 { x_axis: Vec2 { x: n(2), y: n(50) }, y_axis: Vec2 { x: n(-1), y: n(3) } };
    assert_eq!(SdpMatrix2Trait::from_sdp_matrix(skew2), s2);
    assert_eq!(SdpMatrix2Trait::zero().into_matrix(), Mat2Trait::ZERO);
    assert_eq!(SdpMatrix2Trait::identity().into_matrix(), Mat2Trait::IDENTITY);
    assert_eq!(SdpMatrix2Trait::diagonal(n(4)), SdpMatrix2Trait::new(n(4), n(0), n(4)));
    let d2: SdpMatrix2 = Default::default();
    assert_eq!(d2, SdpMatrix2Trait::zero());
    assert!(d2.is_zero());
    assert!(!SdpMatrix2Trait::new(n(0), f(1), n(0)).is_zero());
    assert!(!SdpMatrix2Trait::new(n(0), n(0), f(-1)).is_zero());
}

#[test]
fn test_arithmetic() {
    let s = s_ref();
    let t = SdpMatrix3Trait::diagonal(n(1));
    assert_eq!(s + t, s.add_diagonal(n(1)));
    assert_eq!((s + t) - t, s);
    assert_eq!(s - s, SdpMatrix3Trait::zero());
    assert_eq!(s.mul_scalar(n(2)), s + s);
    assert_eq!(s.mul_scalar(n(0)), SdpMatrix3Trait::zero());
    assert_eq!(
        s.mul_scalar(f(ONE / 2)),
        SdpMatrix3Trait::new(n(1), f(ONE / 2), f(ONE / 4), f(3 * ONE / 2), f(-ONE / 2), n(2)),
    );
    // the floor of `-1 raw * 1/2` is -1 raw
    assert_eq!(SdpMatrix3Trait::diagonal(f(-1)).mul_scalar(f(ONE / 2)).m11, f(-1));
    let v = v3(1, -2, 3);
    assert_eq!(s.mul_vec(v), Vec3 { x: f(3 * ONE / 2), y: n(-8), z: f(29 * ONE / 2) });
    assert_eq!(s.transform_vector(v), s.mul_vec(v));
    assert_eq!(s.mul_vec(v), s.into_matrix().mul_vec3(v));
    let m = m3([1, 2, 3, -1, 0, 2, 4, -3, 1]);
    assert_eq!(s.mul_mat(m), s.into_matrix() * m);
    assert_eq!(s.mul_mat(Mat3Trait::IDENTITY), s.into_matrix());

    let s2 = SdpMatrix2Trait::new(n(2), n(-1), n(3));
    let t2 = SdpMatrix2Trait::identity();
    assert_eq!(s2 + t2, s2.add_diagonal(n(1)));
    assert_eq!((s2 + t2) - t2, s2);
    assert_eq!(s2.mul_scalar(n(-2)), SdpMatrix2Trait::new(n(-4), n(2), n(-6)));
    let w = Vec2 { x: n(3), y: n(4) };
    assert_eq!(s2.mul_vec(w), Vec2 { x: n(2), y: n(9) });
    assert_eq!(s2.mul_vec(w), s2.into_matrix().mul_vec2(w));
}

// ------------------------------------------------------------------------------------------------
// The world-inertia kernel.

/// Signed axis permutations (column-major integer matrices, all rotations) and the permuted
/// diagonal `R diag(2, 3, 5) R^T`: exact.
const PERMUTATIONS: [([i64; 9], [i64; 3]); 7] = [
    ([1, 0, 0, 0, 1, 0, 0, 0, 1], [2, 3, 5]), // 90 degrees about z: x -> y, y -> -x
    ([0, 1, 0, -1, 0, 0, 0, 0, 1], [3, 2, 5]),
    // 90 degrees about x
    ([1, 0, 0, 0, 0, 1, 0, -1, 0], [2, 5, 3]), // 90 degrees about y
    ([0, 0, -1, 0, 1, 0, 1, 0, 0], [5, 3, 2]), // 120 degrees about (1, 1, 1): cyclic permutation
    ([0, 1, 0, 0, 0, 1, 1, 0, 0], [5, 2, 3]),
    ([0, 0, 1, 1, 0, 0, 0, 1, 0], [3, 5, 2]), // 180 degrees about z
    ([-1, 0, 0, 0, -1, 0, 0, 0, 1], [2, 3, 5]),
];

#[test]
fn test_from_rotated_diagonal_permutations() {
    let d = v3(2, 3, 5);
    let mut rows = PERMUTATIONS.span();
    let mut k: u32 = 0;
    while let Some(row) = rows.pop_front() {
        let (r, e) = *row;
        let [ex, ey, ez] = e;
        let s = SdpMatrix3Trait::from_rotated_diagonal_mat3(m3(r), d);
        assert_eq!(s, SdpMatrix3Trait::new(n(ex), n(0), n(0), n(ey), n(0), n(ez)), "perm #{}", k);
        k += 1;
    }
}

#[test]
fn test_from_rotated_diagonal_quat() {
    let d = v3(2, 3, 5);
    let diag = SdpMatrix3Trait::new(n(2), n(0), n(0), n(3), n(0), n(5));
    // identity and the half turns about the axes have exact rotation matrices
    let one = n(1);
    let zero = n(0);
    assert_eq!(SdpMatrix3Trait::from_rotated_diagonal(QuatTrait::IDENTITY, d), diag);
    assert_eq!(
        SdpMatrix3Trait::from_rotated_diagonal(QuatTrait::from_xyzw(one, zero, zero, zero), d),
        diag,
    );
    assert_eq!(
        SdpMatrix3Trait::from_rotated_diagonal(QuatTrait::from_xyzw(zero, one, zero, zero), d),
        diag,
    );
    assert_eq!(
        SdpMatrix3Trait::from_rotated_diagonal(QuatTrait::from_xyzw(zero, zero, -one, zero), d),
        diag,
    );
    // quarter turns: `FRAC_1_SQRT_2^2` is within 0.1 ULP of 1/2, every rotation element is within
    // 1 ULP of 0 / +-1 after the floor, so each output moves by at most
    // `sum_k d_k (|r_ik| + |r_jk|) + 1 <= 2 * 10 + 1` ULP
    let h = FRAC_1_SQRT_2;
    let qz = QuatTrait::from_xyzw(zero, zero, h, h);
    let qx = QuatTrait::from_xyzw(h, zero, zero, h);
    let qy = QuatTrait::from_xyzw(zero, h, zero, h);
    let sz = SdpMatrix3Trait::from_rotated_diagonal(qz, d);
    let sx = SdpMatrix3Trait::from_rotated_diagonal(qx, d);
    let sy = SdpMatrix3Trait::from_rotated_diagonal(qy, d);
    assert!(near3(sz, SdpMatrix3Trait::new(n(3), n(0), n(0), n(2), n(0), n(5)), 21));
    assert!(near3(sx, SdpMatrix3Trait::new(n(2), n(0), n(0), n(5), n(0), n(3)), 21));
    assert!(near3(sy, SdpMatrix3Trait::new(n(5), n(0), n(0), n(3), n(0), n(2)), 21));
    // the quaternion kernel is the matrix kernel on `Mat3::from_quat`
    assert_eq!(sz, SdpMatrix3Trait::from_rotated_diagonal_mat3(Mat3Trait::from_quat(qz), d));
    // an isotropic diagonal is invariant under any rotation, up to the rotation error
    let iso = SdpMatrix3Trait::from_rotated_diagonal(qz, v3(4, 4, 4));
    assert!(near3(iso, SdpMatrix3Trait::diagonal(n(4)), 25));
}

// ------------------------------------------------------------------------------------------------
// Quadratic forms.

#[test]
fn test_quadform() {
    let s = s_ref();
    assert_eq!(s.quadform(Mat3Trait::IDENTITY), s);
    assert_eq!(s.quadform(Mat3Trait::ZERO), SdpMatrix3Trait::zero());
    assert_eq!(
        SdpMatrix3Trait::identity().quadform(Mat3Trait::IDENTITY), SdpMatrix3Trait::identity(),
    );
    // small dyadic entries: the full `Mat3` products are exact and equal
    let m = m3([1, 2, 3, -1, 0, 2, 4, -3, 1]);
    let full = m.transpose() * (s.into_matrix() * m);
    assert_eq!(s.quadform(m).into_matrix(), full);
    // a permutation permutes the entries
    let p = m3([0, 1, 0, 0, 0, 1, 1, 0, 0]);
    assert_eq!(s.quadform(p), SdpMatrix3Trait::new(n(3), n(-1), n(1), n(4), f(ONE / 2), n(2)));
    // `quadform3x2` is `quadform` on the first two columns
    let q2 = s.quadform3x2(n(1), n(-1), n(2), n(0), n(3), n(2));
    let q3 = s.quadform(m);
    assert_eq!(q2, SdpMatrix2Trait::new(q3.m11, q3.m12, q3.m22));
}

// ------------------------------------------------------------------------------------------------
// Inverses.

#[test]
fn test_inverse() {
    assert_eq!(SdpMatrix3Trait::identity().inverse_unchecked(), SdpMatrix3Trait::identity());
    let d = SdpMatrix3Trait::new(n(2), n(0), n(0), n(4), n(0), n(8));
    let dinv = SdpMatrix3Trait::new(f(ONE / 2), n(0), n(0), f(ONE / 4), n(0), f(ONE / 8));
    assert_eq!(d.inverse_unchecked(), dinv);
    assert_eq!(d.inverse(), dinv);
    // [[2, 1, 0.5], [1, 3, -1], [0.5, -1, 4]]: det 17.25, the cofactors are exact, each output is
    // the cofactor divided by 17.25 rounded to nearest
    let s = s_ref();
    let inv = s.inverse_unchecked();
    assert_eq!(inv, s.inverse());
    assert_eq!(inv.into_matrix(), s.into_matrix().inverse());
    assert!((s.into_matrix() * inv.into_matrix()).abs_diff_eq(Mat3Trait::IDENTITY, f(4)));
    // singular matrices: `inverse` returns zero (rapier), `inverse_unchecked` panics (below)
    assert_eq!(SdpMatrix3Trait::zero().inverse(), SdpMatrix3Trait::zero());
    let sing = SdpMatrix3Trait::from_sdp_matrix(m3([1, 2, 3, 2, 4, 6, 3, 6, 9]));
    assert_eq!(sing.inverse(), SdpMatrix3Trait::zero());
    // a determinant below one ULP floors to zero: singular
    assert_eq!(SdpMatrix3Trait::diagonal(f(1)).inverse(), SdpMatrix3Trait::zero());

    let s2 = SdpMatrix2Trait::new(n(2), n(1), n(3));
    let (inv2, det2) = s2.inverse_and_get_determinant_unchecked();
    assert_eq!(det2, n(5));
    assert_eq!(det2, mul_sub(s2.m11, s2.m22, s2.m12, s2.m12));
    assert_eq!(inv2, s2.inverse_unchecked());
    assert_eq!(inv2, s2.inverse());
    assert_eq!(inv2.into_matrix(), s2.into_matrix().inverse());
    assert_eq!(SdpMatrix2Trait::new(n(1), n(2), n(4)).inverse(), SdpMatrix2Trait::zero());
    assert_eq!(
        SdpMatrix2Trait::diagonal(n(4)).inverse_unchecked(), SdpMatrix2Trait::diagonal(f(ONE / 4)),
    );
}

// ------------------------------------------------------------------------------------------------
// Fuzz properties.

#[test]
#[fuzzer(runs: 128, seed: 701)]
fn fuzz_products_match_mat3(a: i64, b: i64, c: i64, d: i64) {
    let s = fuzz_sdp(a, b, c, d);
    let m = fuzz_mat(a, b, c, d);
    let v = m.x_axis;
    // the same `dot3` sums in the same order: bit-identical
    assert_eq!(s.mul_vec(v), s.into_matrix().mul_vec3(v));
    assert_eq!(s.mul_mat(m), s.into_matrix() * m);
    assert_eq!(SdpMatrix3Trait::from_sdp_matrix(s.into_matrix()), s);
    assert_eq!((s + s) - s, s);
    assert_eq!(s.add_diagonal(n(1)), s + SdpMatrix3Trait::identity());
}

#[test]
#[fuzzer(runs: 128, seed: 702)]
fn fuzz_quadform(a: i64, b: i64, c: i64, d: i64) {
    let s = fuzz_sdp(a, b, c, d);
    let m = fuzz_mat(a, b, c, d);
    let q = s.quadform(m);
    // literal parry route: `s * m` floored, then 3 products per output with factors |m| <= 8,
    // floored again: |diff| <= 3 * 8 + 1 ULP
    let full = m.transpose() * s.mul_mat(m);
    assert!(q.into_matrix().abs_diff_eq(full, f(25)));
    // `quadform3x2` is `quadform` of the zero-padded matrix, bit for bit (the floor of the same
    // exact values)
    let q2 = s.quadform3x2(m.x_axis.x, m.y_axis.x, m.x_axis.y, m.y_axis.y, m.x_axis.z, m.y_axis.z);
    let pad = s.quadform(Mat3Trait::from_cols(m.x_axis, m.y_axis, Vec3Trait::ZERO));
    assert_eq!(q2, SdpMatrix2Trait::new(pad.m11, pad.m12, pad.m22));
    assert_eq!(pad.m33, n(0));
}

#[test]
#[fuzzer(runs: 128, seed: 703)]
fn fuzz_from_rotated_diagonal(a: i64, b: i64, c: i64, d: i64) {
    let q = fuzz_quat(a, b, c, d);
    let e = Vec3 {
        x: in_range(a, 0, 4 * ONE), y: in_range(b, 0, 4 * ONE), z: in_range(c, 0, 4 * ONE),
    };
    let r = Mat3Trait::from_quat(q);
    let s = SdpMatrix3Trait::from_rotated_diagonal(q, e);
    assert_eq!(s, SdpMatrix3Trait::from_rotated_diagonal_mat3(r, e));
    // literal rapier / parry route: `R diag(e)` floored, then 3 products per output with factors
    // |r| <= 1 + 2^-31, floored again: |diff| <= sqrt(3) + 1 < 3 ULP
    let literal = r.mul_diagonal_scale(e) * r.transpose();
    assert!(s.into_matrix().abs_diff_eq(literal, f(3)));
    // the trace is invariant: sum of the diagonal = sum of `e`, up to the rotation error
    // (`|r_ik^2 - exact| <= 3` ULP per element, times `e_k <= 4`, 9 elements, 3 floors)
    let trace = s.m11 + s.m22 + s.m33;
    assert!(trace.abs_diff_eq(e.x + e.y + e.z, f(12 * 9 + 3)));
    // a diagonal `e = t * (1, 1, 1)` gives `t * R R^T ~ t * I`
    let iso = SdpMatrix3Trait::from_rotated_diagonal(q, Vec3 { x: e.x, y: e.x, z: e.x });
    assert!(near3(iso, SdpMatrix3Trait::diagonal(e.x), 40));
}

#[test]
#[fuzzer(runs: 128, seed: 704)]
fn fuzz_inverse_identity(a: i64, b: i64, c: i64, d: i64) {
    // eigenvalues in [1, 4): det >= 1, |cofactor| <= 16, each entry of the inverse is within
    // `1 / det + 16 / det^2 + 1/2 <= 17.5` ULP of the exact inverse; `S * S^-1` sums 3 of those
    // errors times |s_ik| (row norm <= 4 sqrt(3)) plus one floor: |diff| <= 122 ULP
    let s = fuzz_spd(a, b, c, d, 3 * ONE);
    let inv = s.inverse_unchecked();
    assert_eq!(inv, s.inverse());
    assert!((s.into_matrix() * inv.into_matrix()).abs_diff_eq(Mat3Trait::IDENTITY, f(122)));
    assert!((s.mul_mat(inv.into_matrix())).abs_diff_eq(Mat3Trait::IDENTITY, f(122)));
}

#[test]
#[fuzzer(runs: 128, seed: 705)]
fn fuzz_inverse_involution(a: i64, b: i64, c: i64, d: i64) {
    // eigenvalues in [1, 2): the first inverse is within 1 + 4 + 1/2 = 5.5 ULP per entry,
    // propagated through the second inversion by at most |S|^2 * 3 * 5.5 = 66 ULP; the second
    // inverse (eigenvalues in (1/2, 1], det >= 1/8, |cofactor| <= 1) adds
    // 8 + 64 + 1/2 ULP: |diff| <= 139 ULP
    let s = fuzz_spd(a, b, c, d, ONE);
    let back = s.inverse_unchecked().inverse_unchecked();
    assert!(near3(back, s, 139));
    // 2x2: the same bounds on the upper-left block
    let s2 = SdpMatrix2Trait::new(s.m11, s.m12, s.m22);
    let back2 = s2.inverse_unchecked().inverse_unchecked();
    assert!(back2.into_matrix().abs_diff_eq(s2.into_matrix(), f(139)));
    let (_, det2) = s2.inverse_and_get_determinant_unchecked();
    assert_eq!(det2, s2.into_matrix().determinant());
}

#[test]
#[fuzzer(runs: 128, seed: 706)]
fn fuzz_sdp2(a: i64, b: i64, c: i64, d: i64) {
    let s = SdpMatrix2Trait::new(cell(a, 0), cell(b, 1), cell(c, 2));
    let v = Vec2 { x: cell(d, 3), y: cell(a, 4) };
    assert_eq!(s.mul_vec(v), s.into_matrix().mul_vec2(v));
    assert_eq!(SdpMatrix2Trait::from_sdp_matrix(s.into_matrix()), s);
    assert_eq!(s.add_diagonal(n(2)) - SdpMatrix2Trait::diagonal(n(2)), s);
    assert_eq!(s.mul_scalar(n(1)), s);
    // the 3D quadratic form restricted to the (x, y) plane is the 2x2 block
    let s3 = SdpMatrix3Trait::new(s.m11, s.m12, cell(d, 5), s.m22, cell(c, 6), cell(b, 7));
    assert_eq!(s3.quadform3x2(n(1), n(0), n(0), n(1), n(0), n(0)), s);
}

// ------------------------------------------------------------------------------------------------
// Panic paths.

// panics: SdpMatrix3::inverse_unchecked
#[test]
#[should_panic(expected: 'SdpMatrix3: singular')]
fn test_inverse_unchecked_singular() {
    let _ = SdpMatrix3Trait::from_sdp_matrix(m3([1, 2, 3, 2, 4, 6, 3, 6, 9])).inverse_unchecked();
}

// panics: SdpMatrix3::inverse_unchecked
#[test]
#[should_panic(expected: 'SdpMatrix3: singular')]
fn test_inverse_unchecked_zero() {
    let _ = SdpMatrix3Trait::zero().inverse_unchecked();
}

// panics: SdpMatrix2::inverse_unchecked
#[test]
#[should_panic(expected: 'SdpMatrix2: singular')]
fn test_inverse_unchecked2_singular() {
    let _ = SdpMatrix2Trait::new(n(1), n(2), n(4)).inverse_unchecked();
}

// panics: SdpMatrix2::inverse_and_get_determinant_unchecked
#[test]
#[should_panic(expected: 'SdpMatrix2: singular')]
fn test_inverse_and_get_determinant2_singular() {
    let _ = SdpMatrix2Trait::zero().inverse_and_get_determinant_unchecked();
}

// panics: SdpMatrix3::mul_scalar
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_scalar_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(100000)).mul_scalar(n(100000));
}

// panics: SdpMatrix2::mul_scalar
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_scalar2_overflow() {
    let _ = SdpMatrix2Trait::diagonal(n(100000)).mul_scalar(n(100000));
}

// panics: SdpMatrix3::mul_vec
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_vec_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(100000)).mul_vec(v3(100000, 0, 0));
}

// panics: SdpMatrix2::mul_vec
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_vec2_overflow() {
    let _ = SdpMatrix2Trait::diagonal(n(100000)).mul_vec(Vec2 { x: n(100000), y: n(0) });
}

// panics: SdpMatrix3::quadform
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_quadform_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(1000)).quadform(Mat3Trait::from_diagonal(v3(2000, 1, 1)));
}

// panics: SdpMatrix3::quadform3x2
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_quadform3x2_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(1000)).quadform3x2(n(2000), n(0), n(0), n(1), n(0), n(0));
}

// panics: SdpMatrix3::from_rotated_diagonal_mat3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_from_rotated_diagonal_overflow() {
    let _ = SdpMatrix3Trait::from_rotated_diagonal_mat3(
        Mat3Trait::from_diagonal(v3(100000, 1, 1)), v3(1, 1, 1),
    );
}

// panics: SdpMatrix3::inverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_overflow() {
    // det = 2^-32 * 1 * 1 = 1 raw, cofactor m11 = 1: 1 / 2^-32 = 2^32 does not fit
    let _ = SdpMatrix3Trait::new(f(1), n(0), n(0), n(1), n(0), n(1)).inverse();
}

// panics: SdpMatrix::SdpMatrix3Add
#[test]
#[should_panic(expected: 'i64_add Overflow')]
fn test_add_overflow() {
    let big = SdpMatrix3Trait::diagonal(f(0x7fffffffffffffff));
    let _ = big + big;
}

// panics: SdpMatrix::SdpMatrix2Sub
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_sub_underflow() {
    let _ = SdpMatrix2Trait::diagonal(f(-0x7fffffffffffffff)) - SdpMatrix2Trait::identity();
}

// panics: SdpMatrix3::add_diagonal
#[test]
#[should_panic(expected: 'i64_add Overflow')]
fn test_add_diagonal_overflow() {
    let _ = SdpMatrix3Trait::diagonal(f(0x7fffffffffffffff)).add_diagonal(f(1));
}

// panics: SdpMatrix2::add_diagonal
#[test]
#[should_panic(expected: 'i64_add Overflow')]
fn test_add_diagonal2_overflow() {
    let _ = SdpMatrix2Trait::diagonal(f(0x7fffffffffffffff)).add_diagonal(f(1));
}

// panics: SdpMatrix::SdpMatrix2Add
#[test]
#[should_panic(expected: 'i64_add Overflow')]
fn test_add2_overflow() {
    let big = SdpMatrix2Trait::diagonal(f(0x7fffffffffffffff));
    let _ = big + big;
}

// panics: SdpMatrix::SdpMatrix3Sub
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_sub3_underflow() {
    let _ = SdpMatrix3Trait::diagonal(f(-0x7fffffffffffffff)) - SdpMatrix3Trait::identity();
}

// panics: SdpMatrix2::inverse_unchecked
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_unchecked2_overflow() {
    // det = 1 raw, cofactor m11 = 1: 2^32 does not fit
    let _ = SdpMatrix2Trait::new(f(1), n(0), n(1)).inverse_unchecked();
}

// panics: SdpMatrix2::inverse_and_get_determinant_unchecked
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_and_get_determinant2_overflow() {
    let _ = SdpMatrix2Trait::new(f(1), n(0), n(1)).inverse_and_get_determinant_unchecked();
}

// panics: SdpMatrix2::inverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse2_overflow() {
    let _ = SdpMatrix2Trait::new(f(1), n(0), n(1)).inverse();
}

// panics: SdpMatrix3::inverse_unchecked
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_unchecked_overflow() {
    let _ = SdpMatrix3Trait::new(f(1), n(0), n(0), n(1), n(0), n(1)).inverse_unchecked();
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_transform_vector_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(100000)).transform_vector(v3(100000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_mat_overflow() {
    let _ = SdpMatrix3Trait::diagonal(n(100000))
        .mul_mat(Mat3Trait::from_diagonal(v3(100000, 1, 1)));
}

// panics: SdpMatrix3::from_rotated_diagonal
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_from_rotated_diagonal_quat_overflow() {
    // a non-unit quaternion: from_quat(2, 0, 0, 0) = diag(1, -7, -7), 49 * 2^26 >= 2^31
    let q = Quat { x: n(2), y: n(0), z: n(0), w: n(0) };
    let _ = SdpMatrix3Trait::from_rotated_diagonal(q, v3(1, 0x4000000, 1));
}
