//! Tests of `glamx::pose3`: constructors and conversions, exact rotations of the axes, the
//! glamx unit tests, the bit-exact equality of the fused kernels with the composed glamx
//! expressions, the measured drift of long composition chains, seeded fuzz properties and one
//! test per panic path.
//!
//! The glamx results themselves are checked by `golden_pose3.cairo` (generated by
//! `tools/refgen` with `DPose3` as the oracle).

use fixed::fixed::{Fixed, FixedTrait};
use glam_core::mat4::{Mat4, Mat4Trait};
use glam_core::quat::{Quat, QuatTrait, quat};
use glam_core::vec3::{Vec3, Vec3Trait, vec3};
use glamx::pose3::{Pose3, Pose3Trait, Rot3Pose3Trait};
use glamx::rot3::Rot3;

const ONE: i64 = 0x100000000;
/// `pi / 2`.
const FRAC_PI_2: i64 = 6746518852;
/// `sqrt(1 / 2)`.
const SQRT_HALF: i64 = 3037000500;

/// A `Fixed` from its raw Q32.32 value.
fn f(raw: i64) -> Fixed {
    FixedTrait::from_raw(raw)
}

/// A `Fixed` from an integer.
fn n(v: i64) -> Fixed {
    FixedTrait::from_raw(v * ONE)
}

fn v3(x: i64, y: i64, z: i64) -> Vec3 {
    vec3(n(x), n(y), n(z))
}

/// A unit quaternion from four raw fuzz inputs: a rotation of `|d| mod tau` around the
/// normalized `(a, b, c)` (the X axis when it is zero).
fn unit_q(a: i64, b: i64, c: i64, d: i64) -> Quat {
    let axis = vec3(f(a % 0x400000000), f(b % 0x400000000), f(c % 0x400000000))
        .normalize_or(Vec3Trait::X);
    QuatTrait::from_axis_angle(axis, f(d % 26986075409))
}

/// A pose from four raw fuzz inputs: `unit_q` and a translation within `|x| < 256`.
fn pose(a: i64, b: i64, c: i64, d: i64) -> Pose3 {
    Pose3Trait::from_parts(
        vec3(f(b % 0x10000000000), f(c % 0x10000000000), f(d % 0x10000000000)), unit_q(a, b, c, d),
    )
}

/// `|q.length_squared() - 1|`, in raw ULP.
fn drift(q: Quat) -> i64 {
    let d = q.length_squared().to_raw() - ONE;
    if d < 0 {
        -d
    } else {
        d
    }
}

// The composed glamx expressions (the `benches::alt::pose3` forms), built on `glam_core::quat` only.

fn composed_transform_point(p: Pose3, v: Vec3) -> Vec3 {
    p.rotation.mul_vec3(v) + p.translation
}

fn composed_inverse_transform_point(p: Pose3, v: Vec3) -> Vec3 {
    p.rotation.conjugate().mul_vec3(v - p.translation)
}

fn composed_inverse(p: Pose3) -> Pose3 {
    let inv = p.rotation.conjugate();
    Pose3 { rotation: inv, translation: inv.mul_vec3(-p.translation) }
}

fn composed_inv_mul(a: Pose3, b: Pose3) -> Pose3 {
    let inv = a.rotation.conjugate();
    Pose3 {
        rotation: inv.mul_quat(b.rotation),
        translation: inv.mul_vec3(b.translation - a.translation),
    }
}

fn composed_mul(a: Pose3, b: Pose3) -> Pose3 {
    Pose3 {
        rotation: a.rotation.mul_quat(b.rotation),
        translation: a.translation + a.rotation.mul_vec3(b.translation),
    }
}

/// Asserts that every fused kernel equals its composed form bit for bit.
fn assert_fused_is_composed(a: Pose3, b: Pose3, v: Vec3) {
    assert_eq!(a.transform_point(v), composed_transform_point(a, v));
    assert_eq!(a.mul_vec3(v), composed_transform_point(a, v));
    assert_eq!(a.inverse_transform_point(v), composed_inverse_transform_point(a, v));
    assert_eq!(a.inverse_transform_vector(v), a.rotation.conjugate().mul_vec3(v));
    assert_eq!(a.transform_vector(v), a.rotation.mul_vec3(v));
    assert_eq!(a.inverse(), composed_inverse(a));
    assert_eq!(a.inv_mul(b), composed_inv_mul(a, b));
    assert_eq!(a * b, composed_mul(a, b));
    assert_eq!(
        a.prepend_translation(v),
        Pose3 { rotation: a.rotation, translation: a.translation + a.rotation.mul_vec3(v) },
    );
}

#[test]
fn test_identity_and_constructors() {
    let id = Pose3 { rotation: QuatTrait::IDENTITY, translation: Vec3Trait::ZERO };
    assert_eq!(Pose3Trait::IDENTITY, id);
    assert_eq!(Pose3Trait::identity(), id);
    assert_eq!(Default::<Pose3>::default(), id);
    let t = v3(1, 2, 3);
    let r = quat(f(0), f(0), f(SQRT_HALF), f(SQRT_HALF));
    assert_eq!(
        Pose3Trait::from_translation(t), Pose3 { rotation: QuatTrait::IDENTITY, translation: t },
    );
    // The associated functions `translation` / `rotation` coexist with the fields of the same
    // name.
    let p = Pose3Trait::translation(n(1), n(2), n(3));
    assert_eq!(p, Pose3Trait::from_translation(t));
    assert_eq!(p.translation, t);
    assert_eq!(Pose3Trait::from_rotation(r), Pose3 { rotation: r, translation: Vec3Trait::ZERO });
    let p = Pose3Trait::from_parts(t, r);
    assert_eq!(p.translation, t);
    assert_eq!(p.rotation, r);
    // A zero axis-angle is the identity rotation.
    assert_eq!(Pose3Trait::new(t, Vec3Trait::ZERO), Pose3Trait::from_translation(t));
    assert_eq!(Pose3Trait::rotation(Vec3Trait::ZERO), id);
    let aa = vec3(f(0), f(0), f(FRAC_PI_2));
    assert_eq!(Pose3Trait::rotation(aa).rotation, QuatTrait::from_scaled_axis(aa));
    assert_eq!(Pose3Trait::rotation(aa).translation, Vec3Trait::ZERO);
    assert_eq!(Pose3Trait::new(t, aa), Pose3Trait::from_parts(t, QuatTrait::from_scaled_axis(aa)));
}

#[test]
fn test_conversions() {
    let t = v3(1, -2, 3);
    let r: Rot3 = quat(f(0), f(SQRT_HALF), f(0), f(SQRT_HALF));
    let p: Pose3 = r.into();
    assert_eq!(p, Pose3Trait::from_rotation(r));
    let p: Pose3 = (t, r).into();
    assert_eq!(p, Pose3Trait::from_parts(t, r));
    let (t2, r2): (Vec3, Rot3) = p.into();
    assert_eq!(t2, t);
    assert_eq!(r2, r);
}

/// Pose, point, `transform_point`, `inverse_transform_point`: rotations by a quarter or a half
/// turn around an axis, whose quaternion components are 0, 1 or `sqrt(1/2)`.
#[test]
fn test_exact_rotations() {
    // Half a turn around Z: every component is exact.
    let p = Pose3Trait::from_parts(v3(1, 2, 3), quat(f(0), f(0), f(ONE), f(0)));
    assert_eq!(p.transform_point(v3(1, 2, 3)), v3(0, 0, 6));
    assert_eq!(p.transform_vector(v3(1, 2, 3)), v3(-1, -2, 3));
    assert_eq!(p.inverse_transform_point(v3(0, 0, 6)), v3(1, 2, 3));
    assert_eq!(p.inverse_transform_vector(v3(-1, -2, 3)), v3(1, 2, 3));
    assert_eq!(p.inverse(), Pose3Trait::from_parts(v3(1, 2, -3), quat(f(0), f(0), f(-ONE), f(0))));
    assert_eq!(
        p * p.inverse(), Pose3Trait::from_parts(Vec3Trait::ZERO, quat(f(0), f(0), f(0), f(ONE))),
    );
    assert_eq!(p.inv_mul(p), Pose3Trait::IDENTITY);
    // Half a turn around X then half a turn around Y is half a turn around Z.
    let rx = Pose3Trait::from_rotation(quat(f(ONE), f(0), f(0), f(0)));
    let ry = Pose3Trait::from_rotation(quat(f(0), f(ONE), f(0), f(0)));
    assert_eq!((ry * rx).transform_vector(v3(1, 2, 3)), v3(-1, -2, 3));
    // The identity pose is exact on any point.
    let v = vec3(f(123456789), f(-987654321), f(0x7fffffff));
    assert_eq!(Pose3Trait::IDENTITY.transform_point(v), v);
    assert_eq!(Pose3Trait::IDENTITY.inverse_transform_point(v), v);
    assert_eq!(Pose3Trait::from_translation(v3(1, 1, 1)).transform_point(v3(1, 2, 3)), v3(2, 3, 4));
    assert_eq!(
        Pose3Trait::from_translation(v3(1, 1, 1)).inverse_transform_point(v3(1, 2, 3)), v3(0, 1, 2),
    );
}

/// The glamx unit tests of `pose3.rs`, at their tolerances converted to raw ULP.
#[test]
fn test_glamx_examples() {
    let eps6: Fixed = f(4295); // 1e-6
    // `test_pose3_transform_point`: a quarter turn around Z then a translation along X.
    let p = Pose3Trait::new(v3(1, 0, 0), vec3(f(0), f(0), f(FRAC_PI_2)));
    assert!(p.transform_point(v3(1, 0, 0)).abs_diff_eq(v3(1, 1, 0), eps6));
    assert!(p.mul_vec3(v3(1, 0, 0)).abs_diff_eq(v3(1, 1, 0), eps6));
    // `test_pose3_transform_vector`: the translation is ignored.
    let p = Pose3Trait::new(v3(100, 200, 300), vec3(f(0), f(0), f(FRAC_PI_2)));
    assert!(p.transform_vector(v3(1, 0, 0)).abs_diff_eq(v3(0, 1, 0), eps6));
    // `test_pose3_inverse` (glamx swaps the arguments of `new`: kept as written).
    let aa = vec3(f(429496730), f(858993459), f(1288490189)); // (0.1, 0.2, 0.3)
    let p = Pose3Trait::new(aa, v3(1, 2, 3));
    let id = p * p.inverse();
    assert!(id.rotation.abs_diff_eq(QuatTrait::IDENTITY, eps6));
    assert!(id.translation.abs_diff_eq(Vec3Trait::ZERO, eps6));
    // `test_pose3_to_from_mat4`.
    let back = Pose3Trait::from_mat4(p.to_mat4());
    assert!(back.rotation.abs_diff_eq(p.rotation, f(42950))); // 1e-5
    assert_eq!(back.translation, p.translation);
    // `test_convert_back_to_equal_pose3`.
    let r = QuatTrait::from_rotation_x(f(3373259426)); // pi / 4
    let p: Pose3 = (v3(1, 2, 3), r).into();
    let (t2, r2): (Vec3, Rot3) = p.into();
    assert_eq!(t2, v3(1, 2, 3));
    assert!(r.dot(r2) > f(ONE - 42950));
}

#[test]
fn test_fused_is_composed() {
    let a = Pose3Trait::from_parts(
        vec3(f(0x180000000), f(-0x1c0000000), f(0x160000000)),
        quat(f(393604950), f(787209899), f(1180814849), f(4034575081)),
    );
    let b = Pose3Trait::from_parts(
        vec3(f(-0x340000000), f(0x280000000), f(0xc0000000)),
        quat(f(-1747086207), f(873543103), f(3494172412), f(1556314705)),
    );
    assert_fused_is_composed(a, b, v3(7, -11, 13));
    assert_fused_is_composed(b, a, vec3(f(-1), f(3), f(-0x12345678)));
    assert_fused_is_composed(Pose3Trait::IDENTITY, a, v3(0, 0, 0));
    // A rotation that is not normalized: the kernels are the same polynomials either way.
    let c = Pose3Trait::from_parts(v3(5, 6, 7), quat(n(1), n(2), n(3), n(4)));
    assert_fused_is_composed(c, a, v3(1, -2, 3));
}

#[test]
fn test_append_prepend_rot3_products() {
    let r = quat(f(0), f(0), f(ONE), f(0));
    let p = Pose3Trait::from_parts(v3(1, 2, 3), r);
    assert_eq!(p.append_translation(v3(1, 1, 1)), Pose3Trait::from_parts(v3(2, 3, 4), r));
    // Local frame: the translation is rotated first.
    assert_eq!(p.prepend_translation(v3(1, 1, 1)), Pose3Trait::from_parts(v3(0, 1, 4), r));
    assert_eq!(p.prepend_translation(v3(1, 1, 1)), p * Pose3Trait::from_translation(v3(1, 1, 1)));
    assert_eq!(p.append_translation(v3(1, 1, 1)), Pose3Trait::from_translation(v3(1, 1, 1)) * p);
    // `Pose3 * Rot3` and `Rot3 * Pose3` are the products with a pure rotation.
    let s = quat(f(ONE), f(0), f(0), f(0));
    assert_eq!(p.mul_rot3(s), p * Pose3Trait::from_rotation(s));
    assert_eq!(s.mul_pose3(p), Pose3Trait::from_rotation(s) * p);
    assert_eq!(
        s.mul_pose3(p), Pose3Trait::from_parts(v3(1, -2, -3), quat(f(0), f(-ONE), f(0), f(0))),
    );
    // The assignment operators.
    let mut q = p;
    q *= p;
    assert_eq!(q, p * p);
    let mut q = p;
    q *= s;
    assert_eq!(q, p.mul_rot3(s));
}

#[test]
fn test_abs_diff_eq() {
    let p = Pose3Trait::from_parts(v3(1, 2, 3), quat(f(0), f(0), f(SQRT_HALF), f(SQRT_HALF)));
    assert!(p.abs_diff_eq(p, f(0)));
    let q = Pose3Trait::from_parts(vec3(n(1), n(2), f(3 * ONE + 5)), p.rotation);
    assert!(p.abs_diff_eq(q, f(5)));
    assert!(!p.abs_diff_eq(q, f(4)));
    let q = Pose3Trait::from_parts(p.translation, quat(f(0), f(-5), f(SQRT_HALF), f(SQRT_HALF)));
    assert!(p.abs_diff_eq(q, f(5)));
    assert!(!p.abs_diff_eq(q, f(4)));
}

#[test]
fn test_lerp_nlerp() {
    let a = Pose3Trait::from_parts(v3(0, 0, 0), QuatTrait::IDENTITY);
    let b = Pose3Trait::from_parts(v3(2, 4, 6), quat(f(0), f(0), f(ONE), f(0)));
    // The translations are interpolated exactly at the ends and at the middle.
    assert_eq!(a.lerp(b, f(0)).translation, a.translation);
    assert_eq!(a.lerp(b, n(1)).translation, b.translation);
    assert_eq!(a.lerp(b, f(ONE / 2)).translation, v3(1, 2, 3));
    assert_eq!(a.nlerp(b, f(ONE / 2)).translation, v3(1, 2, 3));
    // Half-way between the identity and half a turn around Z is a quarter turn around Z, for
    // both interpolations.
    let quarter = quat(f(0), f(0), f(SQRT_HALF), f(SQRT_HALF));
    assert!(a.lerp(b, f(ONE / 2)).rotation.abs_diff_eq(quarter, f(64)));
    assert!(a.nlerp(b, f(ONE / 2)).rotation.abs_diff_eq(quarter, f(4)));
    assert!(a.lerp(b, f(0)).rotation.abs_diff_eq(a.rotation, f(64)));
    assert!(a.nlerp(b, n(1)).rotation.abs_diff_eq(b.rotation, f(4)));
    // `lerp` is `slerp` and `nlerp` is `Quat::lerp` on the rotations.
    let t = f(1431655765);
    assert_eq!(a.lerp(b, t).rotation, a.rotation.slerp(b.rotation, t));
    assert_eq!(a.nlerp(b, t).rotation, a.rotation.lerp(b.rotation, t));
}

#[test]
fn test_to_from_mat4() {
    let p = Pose3Trait::from_parts(v3(1, 2, 3), quat(f(0), f(0), f(ONE), f(0)));
    let m = p.to_mat4();
    assert_eq!(m, Mat4Trait::from_rotation_translation(p.rotation, p.translation));
    assert_eq!(Pose3Trait::from_mat4(m), p);
    assert_eq!(Pose3Trait::from_mat4(Mat4Trait::IDENTITY), Pose3Trait::IDENTITY);
    // The linear part is converted by `Quat::from_mat4`; the translation is the last column.
    let m: Mat4 = Mat4Trait::from_rotation_translation(
        quat(f(393604950), f(787209899), f(1180814849), f(4034575081)), v3(-4, 5, 6),
    );
    let back = Pose3Trait::from_mat4(m);
    assert_eq!(back.rotation, QuatTrait::from_mat4(m));
    assert_eq!(back.translation, v3(-4, 5, 6));
}

/// The rotation of a composition chain is not renormalized: the drift of its squared length,
/// measured here and documented on `Pose3` (0.7 ULP per `Pose3 * Pose3`, much less for
/// `inv_mul`, whose conjugated terms floor in both directions).
#[test]
fn test_composition_drift() {
    let axis = v3(1, 2, 3).normalize();
    let step = Pose3Trait::from_parts(
        vec3(f(0x10000000), f(0), f(0)), QuatTrait::from_axis_angle(axis, f(0x20000000)),
    );
    let axis2 = v3(-2, 1, 4).normalize();
    let step2 = Pose3Trait::from_parts(
        vec3(f(0), f(0x10000000), f(0)), QuatTrait::from_axis_angle(axis2, f(0x30000000)),
    );
    let mut p = step;
    let mut q = step2;
    let mut i: u32 = 0;
    while i != 1000 {
        p = p * step;
        q = step2.inv_mul(q);
        i += 1;
        if i == 100 {
            assert!(drift(p.rotation) <= 64);
        }
    }
    // Measured: 58 ULP after 100 compositions, 278 after 400, 697 after 1 000 (still inside
    // the 1 024 ULP `is_normalized` band); 7 at the end of the `inv_mul` chain (36 at most).
    assert!(drift(p.rotation) <= 700);
    assert!(p.rotation.is_normalized());
    assert!(drift(q.rotation) <= 40);
    // Renormalizing brings the rotation back within 4 ULP.
    assert!(drift(p.rotation.normalize()) <= 4);
}

#[test]
#[fuzzer(runs: 128, seed: 501)]
fn fuzz_fused_is_composed(a: i64, b: i64, c: i64, d: i64) {
    let p = pose(a, b, c, d);
    let q = pose(d, c, b, a);
    let v = vec3(f(c % 0x10000000000), f(a % 0x10000000000), f(b % 0x10000000000));
    assert_fused_is_composed(p, q, v);
}

#[test]
#[fuzzer(runs: 128, seed: 502)]
fn fuzz_inverse(a: i64, b: i64, c: i64, d: i64) {
    let p = pose(a, b, c, d);
    let v = vec3(f(c % 0x10000000000), f(a % 0x10000000000), f(b % 0x10000000000));
    // `p * p^-1` is the identity: the rotation to within the drift of a product (9 ULP), the
    // translation to within the error of two rotations of a vector of length <= 444 by a
    // rotation unit to within 4 ULP (2 * 444 * 4 ULP) plus the floors.
    let id = p * p.inverse();
    assert!(id.rotation.abs_diff_eq(QuatTrait::IDENTITY, f(16)));
    assert!(id.translation.abs_diff_eq(Vec3Trait::ZERO, f(4096)));
    assert!(p.inv_mul(p).abs_diff_eq(Pose3Trait::IDENTITY, f(16)));
    // The inverse transforms undo the direct ones (vectors of length <= 888).
    assert!(p.inverse_transform_point(p.transform_point(v)).abs_diff_eq(v, f(8192)));
    assert!(p.inverse_transform_vector(p.transform_vector(v)).abs_diff_eq(v, f(8192)));
    assert!(p.inverse().transform_point(v).abs_diff_eq(p.inverse_transform_point(v), f(8192)));
    // The inverse of the inverse gives back the rotation exactly.
    assert_eq!(p.inverse().inverse().rotation, p.rotation);
}

#[test]
#[fuzzer(runs: 128, seed: 503)]
fn fuzz_composition(a: i64, b: i64, c: i64, d: i64) {
    let p = pose(a, b, c, d);
    let q = pose(d, c, b, a);
    let r = pose(b, a, d, c);
    let v = vec3(f(c % 0x10000000000), f(a % 0x10000000000), f(b % 0x10000000000));
    assert_eq!(Pose3Trait::IDENTITY * p, p);
    assert_eq!(p * Pose3Trait::IDENTITY, p);
    // Associativity, up to the floors of the products and the non-unit length of the rotations
    // (a few ULP each) scaled by translations of length <= 444.
    assert!(((p * q) * r).abs_diff_eq(p * (q * r), f(8192)));
    // Transforming by a product is transforming twice.
    assert!(
        (p * q).transform_point(v).abs_diff_eq(p.transform_point(q.transform_point(v)), f(8192)),
    );
    // `inv_mul` is `inverse() * rhs`.
    assert!(p.inv_mul(q).abs_diff_eq(p.inverse() * q, f(8192)));
    // Rotating by a pure rotation.
    assert!(r.rotation.mul_pose3(q).abs_diff_eq(Pose3Trait::from_rotation(r.rotation) * q, f(0)));
    assert_eq!(p.mul_rot3(r.rotation), p * Pose3Trait::from_rotation(r.rotation));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_transform_point_overflow() {
    let p = Pose3Trait::from_parts(v3(0x40000000, 0, 0), QuatTrait::IDENTITY);
    p.transform_point(v3(0x40000000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_overflow() {
    let p = Pose3Trait::from_parts(v3(0x40000000, 0, 0), QuatTrait::IDENTITY);
    let _ = p * p;
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_overflow() {
    // The rotation is not unit: the rotated translation leaves the range.
    let p = Pose3Trait::from_parts(v3(0x40000000, 0, 0), quat(f(0), f(0), f(0), n(2)));
    p.inverse();
}

#[test]
#[should_panic(expected: ('i64_sub Overflow',))]
fn test_inverse_transform_point_sub_overflow() {
    let p = Pose3Trait::from_parts(vec3(f(-0x7fffffffffffffff), f(0), f(0)), QuatTrait::IDENTITY);
    p.inverse_transform_point(vec3(f(0x7fffffffffffffff), f(0), f(0)));
}

#[test]
#[should_panic(expected: ('i64_sub Overflow',))]
fn test_inv_mul_sub_overflow() {
    let a = Pose3Trait::from_translation(vec3(f(-0x7fffffffffffffff), f(0), f(0)));
    let b = Pose3Trait::from_translation(vec3(f(0x7fffffffffffffff), f(0), f(0)));
    a.inv_mul(b);
}

#[test]
#[should_panic(expected: ('i64_add Overflow',))]
fn test_append_translation_overflow() {
    let p = Pose3Trait::from_translation(vec3(f(0x7fffffffffffffff), f(0), f(0)));
    p.append_translation(vec3(f(1), f(0), f(0)));
}

#[test]
#[should_panic(expected: 'Quat: normalize zero')]
fn test_nlerp_zero() {
    let z = Pose3Trait::from_parts(Vec3Trait::ZERO, QuatTrait::ZERO);
    z.nlerp(z, f(ONE / 2));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_prepend_translation_overflow() {
    let p = Pose3Trait::from_parts(v3(0x40000000, 0, 0), QuatTrait::IDENTITY);
    p.prepend_translation(v3(0x40000000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inv_mul_overflow() {
    // w = 2: the conjugate rotation scales by 4
    let a = Pose3Trait::from_rotation(quat(f(0), f(0), f(0), n(2)));
    a.inv_mul(Pose3Trait::from_translation(v3(0x20000000, 0, 0)));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_transform_vector_overflow() {
    let p = Pose3Trait::from_rotation(quat(f(0), f(0), f(0), n(2)));
    p.transform_vector(v3(0x20000000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_transform_point_overflow() {
    let p = Pose3Trait::from_rotation(quat(f(0), f(0), f(0), n(2)));
    p.inverse_transform_point(v3(0x20000000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_inverse_transform_vector_overflow() {
    let p = Pose3Trait::from_rotation(quat(f(0), f(0), f(0), n(2)));
    p.inverse_transform_vector(v3(0x20000000, 0, 0));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_to_mat4_overflow() {
    // 1 - 2 y^2 with y = 2^16
    let _ = Pose3Trait::from_rotation(quat(f(0), n(0x10000), f(0), f(0))).to_mat4();
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_mul_rot3_overflow() {
    let big = quat(f(0), f(0), f(0), n(0x40000000));
    Pose3Trait::from_rotation(big).mul_rot3(big);
}

// panics: Rot3Pose3::mul_pose3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rot3_mul_pose3_overflow() {
    let big = quat(f(0), f(0), f(0), n(0x40000000));
    big.mul_pose3(Pose3Trait::from_rotation(big));
}
