//! Tests of `glamx::eigen3`.
//!
//! * `MIRROR`: inputs and bit-exact outputs of the Python mirror (`scripts/gen_eigen3.py
//!   vectors`): the Cairo module and the script that measured its accuracy are the same function.
//! * Eigenvectors are never compared component-wise (their sign and the basis of a repeated
//!   eigenspace are arbitrary): `check` verifies the ascending order, `A v = lambda v`, the
//!   orthonormality, the handedness and the reconstruction `V diag(lambda) V^T = A`.
//! * Tolerances, in raw ULPs, are the documented worst cases of the module (measured by
//!   `scripts/gen_eigen3.py study` over 45 026 matrices, per unit of `|A| = max(1, max |a_ij|)`:
//!   residual 9.6, reconstruction 9.4, orthonormality 3.5 absolute) rounded up to 16 / 16 / 4,
//!   plus the rounding of the test's own arithmetic (stated at each assertion).
//!
//! The eigenvalues are also compared with glamx's f64 `DSymmetricEigen3` and with an f64 Jacobi
//! iteration in `golden_eigen3.cairo` (generated by `tools/refgen`).

use fixed::fixed::{Fixed, FixedTrait};
use glam_core::mat3::{Mat3, Mat3Trait};
use glam_core::vec3::{Vec3, Vec3Trait};
use glamx::eigen3::{Mat3ExtTrait, SymmetricEigen3, SymmetricEigen3Trait};
use glamx::sdp::{SdpMatrix3, SdpMatrix3Trait};

const ONE: i64 = 0x100000000;

/// A `Fixed` from its raw Q32.32 value.
fn f(raw: i64) -> Fixed {
    FixedTrait::from_raw(raw)
}

fn v3(x: i64, y: i64, z: i64) -> Vec3 {
    Vec3 { x: f(x), y: f(y), z: f(z) }
}

/// The symmetric matrix of the 6 raw entries `(a11, a12, a13, a22, a23, a33)`.
fn sdp(a: [i64; 6]) -> SdpMatrix3 {
    let [a11, a12, a13, a22, a23, a33] = a;
    SdpMatrix3Trait::new(f(a11), f(a12), f(a13), f(a22), f(a23), f(a33))
}

fn sym(a: [i64; 6]) -> Mat3 {
    sdp(a).into_matrix()
}

fn abs(x: i64) -> i64 {
    if x < 0 {
        -x
    } else {
        x
    }
}

/// `max(1, ceil(max |a_ij|))`: the unit of the documented error bounds.
fn magnitude(a: Mat3) -> i64 {
    let m = a.abs();
    let top = m.x_axis.max(m.y_axis).max(m.z_axis).max_element().raw;
    top / ONE + 1
}

/// Every invariant of a decomposition `e` of the symmetric matrix `a`.
fn check(a: Mat3, e: SymmetricEigen3) {
    let scale = magnitude(a);
    let l = e.eigenvalues;
    let v = e.eigenvectors;
    assert!(l.x <= l.y && l.y <= l.z, "ascending order");
    // A v = lambda v: documented 16 ULP * |A|, + 1 ULP for the floor of `A v` and 1 for the
    // floor of `lambda v`.
    let tol = f(16 * scale + 2);
    assert!(a.mul_vec3(v.x_axis).abs_diff_eq(v.x_axis.mul_scalar(l.x), tol), "residual 1");
    assert!(a.mul_vec3(v.y_axis).abs_diff_eq(v.y_axis.mul_scalar(l.y), tol), "residual 2");
    assert!(a.mul_vec3(v.z_axis).abs_diff_eq(v.z_axis.mul_scalar(l.z), tol), "residual 3");
    // V^T V = I: documented 4 ULP, + 1 ULP for the floor of each dot product.
    assert!((v.transpose() * v).abs_diff_eq(Mat3Trait::IDENTITY, f(5)), "orthonormality");
    // right-handed: with orthonormal columns the determinant is +1 or -1
    assert!(v.determinant().raw > ONE / 2, "handedness");
    // V diag(lambda) V^T = A: documented 16 ULP * |A|, + 1 ULP for the floor of the exact
    // triple-product sums of `from_rotated_diagonal_mat3`.
    let back = SdpMatrix3Trait::from_rotated_diagonal_mat3(v, l).into_matrix();
    assert!(back.abs_diff_eq(a, f(16 * scale + 1)), "reconstruction");
}
/// `(a11, a12, a13, a22, a23, a33)`, the 3 eigenvalues and the 3 eigenvectors of `new`, the 3
/// eigenvalues of `eigenvalues` (a separate path, see its `#### Deviations`): the upstream unit
/// test, eigenvalues (1, 1, 4), 5 I, an unsorted diagonal, a rank-one matrix, a thin rod inertia,
/// raw entries of a few ULPs, entries of 2^29 (scaled down), an indefinite and a generic matrix.
#[cairofmt::skip]
const MIRROR: [[i64; 21]; 10] = [
    [8589934592, 30064771072, 34359738368, 25769803776, 12884901888, 0, -32663662990, 2480327262, 64543074095, -3067529745, 949329331, 2852328726, 1375737260, -3180081115, 2537947040, 2672892128, 2726279884, 1967178116, -32663662990, 2480327262, 64543074095],
    [8589934592, 4294967296, 4294967296, 8589934592, 4294967296, 8589934592, 4294967296, 4294967296, 17179869184, -1753413057, -1753413057, 3506826112, 3037000500, -3037000500, 0, 2479700525, 2479700525, 2479700526, 4294967296, 4294967296, 17179869184],
    [21474836480, 0, 0, 21474836480, 0, 21474836480, 21474836480, 21474836480, 21474836480, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 21474836480, 21474836480, 21474836480],
    [8589934592, 0, 0, 21474836480, 0, 12884901888, 8589934592, 12884901888, 21474836480, 4294967296, 0, 0, 0, 0, 4294967296, 0, -4294967296, 0, 8589934592, 12884901888, 21474836480],
    [4294967296, 8589934592, 12884901888, 17179869184, 25769803776, 38654705664, 0, 0, 60129542144, 3841535534, -1920767767, 0, 1540040336, 3080080673, -2566733896, 1147878294, 2295756587, 3443634880, 0, 0, 60129542144],
    [35791394, -71582788, 0, 143165576, 0, 178956970, 0, 178956970, 178956970, 3841535534, 1920767767, 0, -1920767767, 3841535534, 0, 0, 0, 4294967296, 0, 178956970, 178956970],
    [3, -2, 1, 0, 5, -4, -8, 2, 4, -774243422, -2431168187, 3454954768, 3001652743, 2155097738, 2189150208, -2972771774, 2809220366, 1310592612, -8, 2, 4],
    [3458764513820540928, 576460752303423488, -1152921504606846976, 2305843009213693952, 288230376151711744, -1729382256910270464, -2011795556202354880, 2178111495894222464, 3868909326432096832, 922329289, -401882574, 4175469214, -1231240855, 4060965624, 662833487, -4009999840, -1339325455, 756870325, -2011795556202354880, 2178111495894222464, 3868909326432096896],
    [-12884901888, 2147483648, -1073741824, 4294967296, 3758096384, 8589934592, -13259352874, 2487542267, 10771810607, 4243642417, -585340199, 309224786, 661412556, 3664454568, -2140338812, 27866607, 2162381477, 3710805018, -13259352874, 2487542267, 10771810607],
    [12345678901, -2345678901, 345678901, 22345678901, -45678901, 32345678901, 11817574471, 22867046980, 32352415251, 4191706232, 933621770, -68507914, -932821835, 4192093453, 54221648, 78653471, -38038832, 4294078569, 11817574471, 22867046980, 32352415251],
];

#[test]
fn test_mirror_vectors() {
    for case in MIRROR.span() {
        let [
            a11,
            a12,
            a13,
            a22,
            a23,
            a33,
            l0,
            l1,
            l2,
            x0,
            x1,
            x2,
            y0,
            y1,
            y2,
            z0,
            z1,
            z2,
            e0,
            e1,
            e2,
        ] =
            *case;
        let a = [a11, a12, a13, a22, a23, a33];
        let expected = SymmetricEigen3 {
            eigenvalues: v3(l0, l1, l2),
            eigenvectors: Mat3 {
                x_axis: v3(x0, x1, x2), y_axis: v3(y0, y1, y2), z_axis: v3(z0, z1, z2),
            },
        };
        let e = SymmetricEigen3Trait::new(sym(a));
        assert_eq!(e, expected);
        assert_eq!(SymmetricEigen3Trait::from_sdp(sdp(a)), expected);
        assert_eq!(sym(a).symmetric_eigen(), expected);
        assert_eq!(SymmetricEigen3Trait::eigenvalues(sym(a)), v3(e0, e1, e2));
        assert_eq!(sym(a).symmetric_eigenvalues(), v3(e0, e1, e2));
        check(sym(a), e);
    }
}

#[test]
fn test_upstream_unit_test() {
    // glamx `eigen_3x3`: eigenvalues -7.6051016780, 0.5774961930, 15.0276054850 (10 decimals,
    // 0.22 ULP), quantized. Documented bound: 0.79 ULP * |A| = 7 ULP for |A| = 8.
    let a = sym([2 * ONE, 7 * ONE, 8 * ONE, 6 * ONE, 3 * ONE, 0]);
    let l = a.symmetric_eigenvalues();
    assert!(l.abs_diff_eq(v3(-32663662990, 2480327262, 64543074095), f(7)));
    assert!(SymmetricEigen3Trait::new(a).eigenvalues.abs_diff_eq(l, f(1)));
}

#[test]
fn test_degenerate_cases() {
    // zero matrix and `Default`
    let zero = SymmetricEigen3Trait::new(sym([0, 0, 0, 0, 0, 0]));
    assert_eq!(zero.eigenvalues, Vec3Trait::ZERO);
    assert_eq!(zero.eigenvectors, Mat3Trait::IDENTITY);
    assert_eq!(zero, Default::default());
    // multiplicity 3 (glamx `eigen_3x3_identity`, `eigen_3x3_uniform_scaling`): exact eigenvalues
    // and the identity basis, from 1 ULP to the largest scaled-up magnitude
    for r in [1, -1, ONE, 5 * ONE, -7 * ONE, 0x3ffffffffffffff].span() {
        let e = SymmetricEigen3Trait::new(sym([*r, 0, 0, *r, 0, *r]));
        assert_eq!(e.eigenvalues, v3(*r, *r, *r));
        assert_eq!(e.eigenvectors, Mat3Trait::IDENTITY);
    }
    // diagonal (glamx `eigen_3x3_diagonal`): exact eigenvalues, the eigenvectors are the axes
    let e = SymmetricEigen3Trait::new(sym([2 * ONE, 0, 0, 5 * ONE, 0, 3 * ONE]));
    assert_eq!(e.eigenvalues, v3(2 * ONE, 3 * ONE, 5 * ONE));
    assert_eq!(e.eigenvectors.x_axis, Vec3Trait::X);
    assert_eq!(e.eigenvectors.y_axis, Vec3Trait::Z);
    assert_eq!(e.eigenvectors.z_axis, -Vec3Trait::Y);
    // multiplicity 2 off the axes: [[2, 1, 1], [1, 2, 1], [1, 1, 2]] has eigenvalues (1, 1, 4)
    let e = SymmetricEigen3Trait::new(sym([2 * ONE, ONE, ONE, 2 * ONE, ONE, 2 * ONE]));
    assert_eq!(e.eigenvalues, v3(ONE, ONE, 4 * ONE));
    // rank one: u u^T with u = (1, 2, 3) has eigenvalues (0, 0, 14)
    let e = SymmetricEigen3Trait::new(sym([ONE, 2 * ONE, 3 * ONE, 4 * ONE, 6 * ONE, 9 * ONE]));
    assert_eq!(e.eigenvalues, v3(0, 0, 14 * ONE));
    // a single off-diagonal ULP: eigenvalues (-1, 0, 1) ULP
    let e = SymmetricEigen3Trait::new(sym([0, 1, 0, 0, 0, 0]));
    assert_eq!(e.eigenvalues, v3(-1, 0, 1));
}

#[test]
fn test_extreme_magnitudes() {
    // 2^26 and above: scaled down by 2^6, eigenvalues are multiples of 64 ULP
    let top = 0x7fffffffffffffff;
    let e = SymmetricEigen3Trait::new(sym([top, 0, 0, top, 0, top]));
    assert_eq!(e.eigenvalues, v3(top - 63, top - 63, top - 63));
    let e = SymmetricEigen3Trait::new(sym([-top, 0, 0, 5, 0, 7]));
    assert_eq!(e.eigenvalues, v3(-top - 1, 0, 0));
    // all entries 2^29: eigenvalues (0, 0, 3 * 2^29), the largest that never overflows
    let r = 0x2000000000000000;
    let e = SymmetricEigen3Trait::new(sym([r, r, r, r, r, r]));
    assert_eq!(e.eigenvalues, v3(0, 0, 3 * r));
    check(sym([r, r, r, r, r, r]), e);
}

#[test]
fn test_reads_the_upper_triangle() {
    let a = sym([2 * ONE, 7 * ONE, 8 * ONE, 6 * ONE, 3 * ONE, 0]);
    let mut lower = a;
    lower.x_axis.y = f(123);
    lower.x_axis.z = f(-456);
    lower.y_axis.z = f(789);
    assert_eq!(SymmetricEigen3Trait::new(lower), SymmetricEigen3Trait::new(a));
    assert_eq!(lower.symmetric_eigenvalues(), a.symmetric_eigenvalues());
}

#[test]
fn test_reverse() {
    let e = SymmetricEigen3Trait::new(sym([2 * ONE, 7 * ONE, 8 * ONE, 6 * ONE, 3 * ONE, 0]));
    let r = e.reverse();
    assert_eq!(r.eigenvalues, v3(e.eigenvalues.z.raw, e.eigenvalues.y.raw, e.eigenvalues.x.raw));
    assert_eq!(r.eigenvectors.x_axis, e.eigenvectors.z_axis);
    assert_eq!(r.eigenvectors.y_axis, e.eigenvectors.y_axis);
    assert_eq!(r.eigenvectors.z_axis, e.eigenvectors.x_axis);
    assert_eq!(r.reverse(), e);
}

#[test]
fn test_swap_cols() {
    // glamx `test_mat3_swap_cols`
    let (c0, c1, c2) = (v3(1, 2, 3), v3(4, 5, 6), v3(7, 8, 9));
    let mut m = Mat3 { x_axis: c0, y_axis: c1, z_axis: c2 };
    m.swap_cols(0, 2);
    assert_eq!(m, Mat3 { x_axis: c2, y_axis: c1, z_axis: c0 });
    m.swap_cols(1, 0);
    assert_eq!(m, Mat3 { x_axis: c1, y_axis: c2, z_axis: c0 });
    m.swap_cols(2, 2);
    assert_eq!(m, Mat3 { x_axis: c1, y_axis: c2, z_axis: c0 });
    // parry `with_inertia_matrix`: swapping two columns flips the handedness
    let mut v = SymmetricEigen3Trait::new(sym([2 * ONE, ONE, 0, 3 * ONE, ONE, 4 * ONE]))
        .eigenvectors;
    v.swap_cols(1, 2);
    assert!(v.determinant().raw < -ONE / 2);
}

// ------------------------------------------------------------------------------------------------
// Fuzz properties.

/// The `k`-th fuzzed raw entry, |value| <= 8.
fn cell(v: i64, k: i64) -> i64 {
    (v / (k + 1) + k * 2654435761) % 0x800000000
}

fn fuzz_sym(a: i64, b: i64, c: i64) -> [i64; 6] {
    [cell(a, 0), cell(b, 1), cell(c, 2), cell(b, 3), cell(a, 4), cell(c, 5)]
}

#[test]
#[fuzzer(runs: 128, seed: 801)]
fn fuzz_decomposition(a: i64, b: i64, c: i64) {
    let s = fuzz_sym(a, b, c);
    let e = SymmetricEigen3Trait::new(sym(s));
    check(sym(s), e);
    assert_eq!(SymmetricEigen3Trait::from_sdp(sdp(s)), e);
    // the trace is the sum of the eigenvalues: 3 * 0.79 ULP * |A| with |A| <= 8
    let l = e.eigenvalues;
    let [a11, _, _, a22, _, a33] = s;
    assert!(abs(l.x.raw + l.y.raw + l.z.raw - a11 - a22 - a33) <= 19);
    // `eigenvalues` skips the polish of the eigenvectors: 1 ULP from `new` at most (measured)
    assert!(SymmetricEigen3Trait::eigenvalues(sym(s)).abs_diff_eq(l, f(1)));
}

/// `16^k` for `k` in `0..12`.
const POW16: [i64; 12] = [
    0x1, 0x10, 0x100, 0x1000, 0x10000, 0x100000, 0x1000000, 0x10000000, 0x100000000, 0x1000000000,
    0x10000000000, 0x100000000000,
];

#[test]
#[fuzzer(runs: 128, seed: 802)]
fn fuzz_magnitudes(a: i64, b: i64, c: i64, k: u8) {
    // entries below 2^(4 + 4 k) raw: from a few ULPs to 2^16
    let p = *POW16.span()[(k % 12).into()];
    let [a11, a12, a13, a22, a23, a33] = fuzz_sym(a, b, c);
    let q = 0x80000000;
    let s = [a11 / q * p, a12 / q * p, a13 / q * p, a22 / q * p, a23 / q * p, a33 / q * p];
    check(sym(s), SymmetricEigen3Trait::new(sym(s)));
}

#[test]
#[fuzzer(runs: 128, seed: 803)]
fn fuzz_scale_covariance(a: i64, b: i64, c: i64) {
    // 16 A falls in the next scale bucket: the scaled matrix, hence the rotations and the
    // eigenvectors, are identical bit for bit; each eigenvalue is rounded from the same scaled
    // value at two resolutions, 16 * 1/2 ULP apart at most.
    let [a11, a12, a13, a22, a23, a33] = fuzz_sym(a, b, c);
    let e = SymmetricEigen3Trait::new(sym([a11, a12, a13, a22, a23, a33]));
    let big = [16 * a11, 16 * a12, 16 * a13, 16 * a22, 16 * a23, 16 * a33];
    let e16 = SymmetricEigen3Trait::new(sym(big));
    assert_eq!(e16.eigenvectors, e.eigenvectors);
    assert!(e16.eigenvalues.abs_diff_eq(e.eigenvalues.mul_scalar(f(16 * ONE)), f(8)));
}

#[test]
#[fuzzer(runs: 128, seed: 804)]
fn fuzz_diagonal_is_exact(a: i64, b: i64, c: i64) {
    // below 2^26 a diagonal matrix is never rotated: sorted entries, signed axes
    let (x, y, z) = (a % 0x400000000000000, b % 0x400000000000000, c % 0x400000000000000);
    let e = SymmetricEigen3Trait::new(sym([x, 0, 0, y, 0, z]));
    let l = e.eigenvalues;
    assert!(l.x <= l.y && l.y <= l.z);
    assert_eq!(l.x.raw + l.y.raw + l.z.raw, x + y + z);
    assert!(l.x.raw == x || l.x.raw == y || l.x.raw == z);
    assert!(l.z.raw == x || l.z.raw == y || l.z.raw == z);
    let v = e.eigenvectors;
    assert_eq!(v.transpose() * v, Mat3Trait::IDENTITY);
    assert_eq!(v.determinant().raw, ONE);
    // no rotation: `eigenvalues` returns the same sorted diagonal
    assert_eq!(SymmetricEigen3Trait::eigenvalues(sym([x, 0, 0, y, 0, z])), l);
}

#[test]
#[fuzzer(runs: 128, seed: 805)]
fn fuzz_two_equal_eigenvalues(a: i64, b: i64, c: i64) {
    // A = l1 I + (l2 - l1) n n^T: eigenvalues (l1, l1, l2) up to the quantization of A. Each
    // entry is off by 1 ULP (floor) + 2 * 1 ULP * |l2 - l1| (the rounding of `n`, |n_i| <= 1,
    // |l2 - l1| <= 16), i.e. 33 ULP; Weyl: eigenvalues move by at most 3 * 33 ULP, + 13 ULP for
    // the documented 0.79 ULP * |A| (|A| <= 16).
    let n = Vec3 { x: f(cell(a, 0) + 1), y: f(cell(b, 1)), z: f(cell(c, 2)) }.normalize();
    let (l1, l2) = (f(cell(c, 3)), f(cell(a, 4)));
    let d = l2 - l1;
    let s = SdpMatrix3Trait::new(
        l1 + d * n.x * n.x,
        d * n.x * n.y,
        d * n.x * n.z,
        l1 + d * n.y * n.y,
        d * n.y * n.z,
        l1 + d * n.z * n.z,
    );
    let e = SymmetricEigen3Trait::from_sdp(s);
    check(s.into_matrix(), e);
    let expected = if l1 <= l2 {
        Vec3 { x: l1, y: l1, z: l2 }
    } else {
        Vec3 { x: l2, y: l1, z: l1 }
    };
    assert!(e.eigenvalues.abs_diff_eq(expected, f(112)));
}

// ------------------------------------------------------------------------------------------------
// Panic paths.

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_new_eigenvalue_overflow() {
    // all entries 2^30: the largest eigenvalue, 3 * 2^30, does not fit
    let r = 0x4000000000000000;
    let _ = SymmetricEigen3Trait::new(sym([r, r, r, r, r, r]));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_new_min_entry() {
    let _ = SymmetricEigen3Trait::new(sym([-0x8000000000000000, 0, 0, 0, 0, 0]));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_from_sdp_eigenvalue_overflow() {
    let r = 0x4000000000000000;
    let _ = SymmetricEigen3Trait::from_sdp(sdp([r, r, r, r, r, r]));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_eigenvalues_overflow() {
    let r = 0x4000000000000000;
    let _ = SymmetricEigen3Trait::eigenvalues(sym([r, r, r, r, r, r]));
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_symmetric_eigen_overflow() {
    let r = 0x4000000000000000;
    let _ = sym([r, r, r, r, r, r]).symmetric_eigen();
}

#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_symmetric_eigenvalues_overflow() {
    let r = 0x4000000000000000;
    let _ = sym([r, r, r, r, r, r]).symmetric_eigenvalues();
}

#[test]
#[should_panic(expected: 'Mat3: index out of bounds')]
fn test_swap_cols_first_index_out_of_bounds() {
    let mut m = Mat3Trait::IDENTITY;
    m.swap_cols(3, 0);
}

#[test]
#[should_panic(expected: 'Mat3: index out of bounds')]
fn test_swap_cols_second_index_out_of_bounds() {
    let mut m = Mat3Trait::IDENTITY;
    m.swap_cols(0, 3);
}
