#!/usr/bin/env python3
"""Generate the glamx gas tables in the root and package READMEs from gas/*.snap."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAS = ROOT / "gas"
BEGIN = "<!-- gas:begin -->"
END = "<!-- gas:end -->"
METRICS = ["l2_gas", "steps", "range_check", "bitwise", "other_builtins"]

TABLES = [
    ("`Pose3`", [
        ("`mul_pose3`", "pose3::mul_pose3"),
        ("`inv_mul`", "pose3::inv_mul"),
        ("`inverse`", "pose3::inverse"),
        ("`transform_point`", "pose3::transform_point"),
        ("`transform_vector`", "pose3::transform_vector"),
        ("`inverse_transform_point`", "pose3::inverse_transform_point"),
        ("`nlerp`", "pose3::nlerp"),
        ("`to_mat4`", "pose3::to_mat4"),
    ]),
    ("`Pose2`", [
        ("`mul`", "pose2::mul"),
        ("`inv_mul`", "pose2::inv_mul"),
        ("`inverse`", "pose2::inverse"),
        ("`transform_point`", "pose2::transform_point"),
        ("`transform_vector`", "pose2::transform_vector"),
    ]),
    ("`Rot2`", [
        ("`mul`", "rot2::mul"),
        ("`mul_vec2`", "rot2::mul_vec2"),
        ("`inverse`", "rot2::inverse"),
        ("`from_angle`", "rot2::from_angle"),
        ("`angle`", "rot2::angle"),
        ("`normalize`", "rot2::normalize"),
        ("`lerp`", "rot2::lerp"),
        ("`slerp`", "rot2::slerp"),
    ]),
    ("`SdpMatrix3`", [
        ("`mul_vec`", "sdp::mul_vec"),
        ("`mul_mat`", "sdp::mul_mat"),
        ("`add`", "sdp::add"),
        ("`quadform`", "sdp::quadform"),
        ("`inverse_regular`", "sdp::inverse_regular"),
        ("`from_rotated_diagonal`", "sdp::from_rotated_diagonal"),
    ]),
    ("`SymmetricEigen3`", [
        ("`new` (generic)", "eigen3::new_generic"),
        ("`new` (diagonal)", "eigen3::new_diagonal"),
        ("`eigenvalues` (generic)", "eigen3::eigenvalues_generic"),
    ]),
]


def group(value: int) -> str:
    return f"{value:,}".replace(",", " ")


def toolchain() -> str:
    tools = []
    for line in (ROOT / ".tool-versions").read_text().splitlines():
        fields = line.split("#")[0].split()
        if len(fields) >= 2:
            tools.append(f"{fields[0]} {fields[1]}")
    return ", ".join(tools)


def snapshots() -> dict[str, dict[str, int]]:
    rows = {}
    for path in sorted(GAS.glob("*.snap")):
        for line in path.read_text().splitlines():
            if not line or line.startswith("#"):
                continue
            name, values = line.rsplit(":", 1)
            rows[name.removeprefix("bench_")] = dict(zip(METRICS, map(int, values.split())))
    return rows


def render(prefix: str, rows: dict[str, dict[str, int]]) -> str:
    out = [
        "Sierra gas (`l2 gas`, what a transaction pays) and prover cost (steps, range checks) "
        "of one call, net of the test overhead (`X__op - X__base`, see "
        f"[`scripts/bench.py`]({prefix}scripts/bench.py)), measured with {toolchain()} "
        "(`.tool-versions`). Source of truth: `gas/*.snap`; this region is generated by "
        "`scripts/gas_tables.py`, do not edit it.",
        "",
    ]
    missing = []
    for title, entries in TABLES:
        rendered = []
        for label, key in entries:
            row = rows.get(key)
            if row is None:
                missing.append(key)
                continue
            rendered.append(
                f"| {label} | {group(row['l2_gas'])} | {group(row['steps'])} | "
                f"{group(row['range_check'])} |"
            )
        if rendered:
            out.extend([
                f"### {title}", "", "| op | l2 gas | steps | range checks |",
                "|---|---:|---:|---:|", *rendered, "",
            ])
    if missing:
        sys.exit("gas_tables.py: missing snapshot rows:\n  " + "\n  ".join(missing))
    return "\n".join(out).rstrip()


def replace_region(path: Path, body: str) -> str:
    text = path.read_text()
    begin, end = text.find(BEGIN), text.find(END)
    if begin < 0 or end < begin or text.count(BEGIN) != 1 or text.count(END) != 1:
        sys.exit(f"{path.relative_to(ROOT)}: needs exactly one {BEGIN} ... {END} region")
    return text[:begin + len(BEGIN)] + "\n\n" + body + "\n\n" + text[end:]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = snapshots()
    outputs = {
        ROOT / "README.md": render("", rows),
        ROOT / "packages/glamx/README.md": render("../../", rows),
    }
    stale = []
    for path, body in outputs.items():
        new = replace_region(path, body)
        if new != path.read_text():
            stale.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.write_text(new)
    if args.check and stale:
        sys.exit(
            "stale gas tables: " + ", ".join(stale)
            + "\nrun `python3 scripts/gas_tables.py` and commit the result"
        )
    print("gas tables are up to date" if args.check else "rewrote: " + (", ".join(stale) or "nothing"))


if __name__ == "__main__":
    main()
