//! Cairo emission. The output is already formatted (`scarb fmt --check` passes on it): data
//! tables are `#[cairofmt::skip]` constants, everything else is short straight-line code.

use std::collections::{BTreeMap, BTreeSet};

use crate::cases::{self, FunctionCases};
use crate::registry::Registry;
use crate::spec::{FunctionSpec, Spec};
use crate::types::{Layouts, Leaf, Ty};
use crate::value::Value;

pub const STUB: &str = "// GENERATED by tools/refgen - do not edit by hand.\n";
const MAX_LINE: usize = 100;

/// Generates the whole golden file of a module.
pub fn module(spec: &Spec, registry: Option<&Registry>) -> Result<String, String> {
    let enabled: Vec<&FunctionSpec> = spec
        .functions
        .iter()
        .filter(|f| spec.enabled && f.enabled)
        .collect();
    if enabled.is_empty() {
        return Ok(STUB.to_owned());
    }
    let registry = registry
        .ok_or_else(|| format!("tools/refgen/src/oracles/{}.rs does not exist", spec.module))?;
    let layouts = Layouts::new(&spec.types)?;

    let mut generated = Vec::new();
    for f in &enabled {
        let fc = cases::generate(spec, f, registry)
            .map_err(|e| format!("function {:?}: {e}", f.name))?;
        generated.push((*f, fc));
    }

    // Helpers actually used (an unused private function is a lint error).
    let mut next: BTreeSet<Ty> = BTreeSet::new();
    let mut check: BTreeSet<Ty> = BTreeSet::new();
    for (_, fc) in &generated {
        fc.arg_tys
            .iter()
            .for_each(|t| require(t, &layouts, &mut next));
        if !fc.cases.is_empty() {
            require(&fc.ret, &layouts, &mut check);
        }
    }

    let mut out = String::from(STUB);
    out.push_str(&format!(
        "// Oracle: glam-rs 0.33.8 (f64) on inputs quantized to Q32.32. Sources:\n\
         // tools/refgen/specs/{m}.toml and tools/refgen/src/oracles/{m}.rs\n\
         // Regenerate: cargo run --manifest-path tools/refgen/Cargo.toml -- gen {m}\n\n",
        m = spec.module
    ));
    out.push_str(&imports(spec, &layouts, &next, &check)?);
    let mut items = helpers(&layouts, &next, &check);
    for (f, fc) in &generated {
        items.extend(function(spec, &layouts, f, fc));
    }
    // The formatter glues a `#[cairofmt::skip]` item (and its comment) to the previous item.
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(if item.glued { "\n" } else { "\n\n" });
        }
        out.push_str(item.text.trim_end());
    }
    out.push('\n');

    for (i, line) in out.lines().enumerate() {
        if line.chars().count() > MAX_LINE {
            return Err(format!(
                "generated line {} is longer than {MAX_LINE} characters (shorten the `call` \
                 expression): {line}",
                i + 1
            ));
        }
    }
    Ok(out)
}

/// A top-level item of the generated file.
struct Item {
    text: String,
    /// True for data tables: no blank line before them.
    glued: bool,
}

fn item(text: String) -> Item {
    Item { text, glued: false }
}

/// Adds `ty` and every type its helper depends on.
fn require(ty: &Ty, layouts: &Layouts, set: &mut BTreeSet<Ty>) {
    if let Ty::Tuple(elems) = ty {
        elems.iter().for_each(|t| require(t, layouts, set));
        return;
    }
    if !set.insert(ty.clone()) {
        return;
    }
    if let Some(layout) = layouts.layout(ty) {
        layout
            .fields
            .iter()
            .for_each(|(_, t)| require(t, layouts, set));
    }
}

fn imports(
    spec: &Spec,
    layouts: &Layouts,
    next: &BTreeSet<Ty>,
    check: &BTreeSet<Ty>,
) -> Result<String, String> {
    let mut paths: BTreeSet<String> = spec.imports.iter().cloned().collect();
    // `check_*` of a struct only reads fields and never names the type of its fields, but
    // its signature names the struct itself; `next_*` names every struct it builds.
    for ty in next.iter().chain(check) {
        if let Some(path) = layouts.path(ty) {
            paths.insert(path);
        }
    }
    let mut groups: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for path in paths {
        let (parent, item) = path
            .rsplit_once("::")
            .ok_or_else(|| format!("import {path:?} must be a full path such as `fixed::Fixed`"))?;
        // One item, optionally renamed (`path::Item as Alias`) to keep long calls within 100
        // columns.
        let bare = item.split_once(" as ").map_or(item, |(name, alias)| {
            if alias.contains(' ') { " " } else { name }
        });
        if item.contains(['{', '}']) || bare.contains(' ') {
            return Err(format!(
                "import {path:?}: list one item per entry, without braces"
            ));
        }
        groups
            .entry(parent.to_owned())
            .or_default()
            .insert(item.to_owned());
    }
    // `scarb fmt` sorts the `use` lines by their text, where `{` sorts after every letter:
    // `use fixed::wide::X;` comes before `use fixed::{A, B};`.
    let mut uses: Vec<String> = groups
        .into_iter()
        .map(|(parent, items)| {
            let items: Vec<String> = items.into_iter().collect();
            if items.len() == 1 {
                format!("{parent}::{}", items[0])
            } else {
                format!("{parent}::{{{}}}", items.join(", "))
            }
        })
        .collect();
    uses.sort();
    let mut out = String::new();
    for path in uses {
        out.push_str(&format!("use {path};\n"));
    }
    if !out.is_empty() {
        out.push('\n');
    }
    Ok(out)
}

fn helpers(layouts: &Layouts, next: &BTreeSet<Ty>, check: &BTreeSet<Ty>) -> Vec<Item> {
    let mut items = Vec::new();
    if next.is_empty() && check.is_empty() {
        return items;
    }
    items.push(item(
        "fn next_i64(ref d: Span<i64>) -> i64 {\n    *d.pop_front().unwrap()\n}".into(),
    ));
    for ty in next {
        let name = ty.snake();
        let cairo = layouts.cairo(ty);
        let body = match ty.leaf() {
            Some(Leaf::I64) => continue,
            Some(Leaf::Fixed) => "    Fixed { raw: next_i64(ref d) }\n".to_owned(),
            Some(Leaf::I32 | Leaf::U32) => "    next_i64(ref d).try_into().unwrap()\n".to_owned(),
            Some(Leaf::Bool) => "    next_i64(ref d) != 0\n".to_owned(),
            None => {
                let layout = layouts.layout(ty).expect("struct");
                let mut body = String::new();
                for (field, fty) in &layout.fields {
                    body.push_str(&format!("    let {field} = next_{}(ref d);\n", fty.snake()));
                }
                let fields: Vec<&str> = layout.fields.iter().map(|(f, _)| f.as_str()).collect();
                body.push_str(&format!("    {cairo} {{ {} }}\n", fields.join(", ")));
                body
            }
        };
        items.push(item(format!(
            "fn next_{name}(ref d: Span<i64>) -> {cairo} {{\n{body}}}"
        )));
    }
    if check.is_empty() {
        return items;
    }
    items.push(item(
        "fn check_raw(actual: i64, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {\n    \
         let expected = next_i64(ref d);\n    \
         let diff: i128 = actual.into() - expected.into();\n    \
         let diff = if diff < 0 {\n        -diff\n    } else {\n        diff\n    };\n    \
         assert!(diff <= tol, \"{name} #{case}: got {actual}, expected {expected} (tol {tol})\");\n}"
            .into(),
    ));
    for ty in check {
        let name = ty.snake();
        let cairo = layouts.cairo(ty);
        let tol = if ty.has_fixed_leaf() {
            "tol: i128, "
        } else {
            ""
        };
        let body = match ty.leaf() {
            Some(Leaf::Fixed) => "    check_raw(actual.raw, ref d, tol, name, case);\n".to_owned(),
            Some(Leaf::I64) => "    check_raw(actual, ref d, 0, name, case);\n".to_owned(),
            Some(Leaf::I32 | Leaf::U32) => {
                "    check_raw(actual.into(), ref d, 0, name, case);\n".to_owned()
            }
            Some(Leaf::Bool) => {
                "    let value = if actual {\n        1\n    } else {\n        0\n    };\n    \
                                 check_raw(value, ref d, 0, name, case);\n"
                    .to_owned()
            }
            None => {
                let layout = layouts.layout(ty).expect("struct");
                let mut body = String::new();
                for (field, fty) in &layout.fields {
                    let tol = if fty.has_fixed_leaf() { "tol, " } else { "" };
                    body.push_str(&format!(
                        "    check_{}(actual.{field}, ref d, {tol}name, case);\n",
                        fty.snake()
                    ));
                }
                body
            }
        };
        items.push(item(format!(
            "fn check_{name}(actual: {cairo}, ref d: Span<i64>, {tol}name: @ByteArray, case: usize) {{\n{body}}}"
        )));
    }
    items
}

fn next_expr(ty: &Ty) -> String {
    match ty {
        Ty::Tuple(elems) => {
            let parts: Vec<String> = elems.iter().map(next_expr).collect();
            format!("({})", parts.join(", "))
        }
        other => format!("next_{}(ref d)", other.snake()),
    }
}

fn call_expr(f: &FunctionSpec) -> String {
    let mut call = f.call.clone();
    // Highest index first so that `{1}` never matches inside `{10}`.
    for i in (0..f.args.len()).rev() {
        call = call.replace(&format!("{{{i}}}"), &format!("a{i}"));
    }
    call
}

/// A `#[cairofmt::skip]` table: one case per row (inputs then expected leaves). A row that
/// does not fit the line limit is wrapped, the expected leaves starting on their own line.
fn table(name: &str, rows: &[(Vec<i64>, Vec<i64>)]) -> String {
    let total: usize = rows.iter().map(|(a, e)| a.len() + e.len()).sum();
    let mut out = format!("#[cairofmt::skip]\nconst {name}: [i64; {total}] = [\n");
    let join = |leaves: &[i64]| {
        leaves
            .iter()
            .map(|l| format!("{l},"))
            .collect::<Vec<_>>()
            .join(" ")
    };
    let wrapped = |leaves: &[i64], first_indent: &str, out: &mut String| {
        let mut indent = first_indent;
        let mut line = String::new();
        for leaf in leaves {
            let token = format!("{leaf},");
            if !line.is_empty() && indent.len() + line.len() + 1 + token.len() > MAX_LINE {
                out.push_str(&format!("{indent}{line}\n"));
                line.clear();
                indent = "        ";
            }
            if !line.is_empty() {
                line.push(' ');
            }
            line.push_str(&token);
        }
        if !line.is_empty() {
            out.push_str(&format!("{indent}{line}\n"));
        }
    };
    for (args, expected) in rows {
        let single = join(&[args.as_slice(), expected.as_slice()].concat());
        if 4 + single.len() <= MAX_LINE {
            out.push_str(&format!("    {single}\n"));
        } else {
            wrapped(args, "    ", &mut out);
            wrapped(expected, "        ", &mut out);
        }
    }
    out.push_str("];\n");
    out
}

fn wrap_comment(text: &str) -> String {
    let mut out = String::new();
    let mut line = String::from("//");
    for word in text.split_whitespace() {
        if line.len() + 1 + word.len() > MAX_LINE - 2 && line != "//" {
            out.push_str(&line);
            out.push('\n');
            line = String::from("//");
        }
        line.push(' ');
        line.push_str(word);
    }
    out.push_str(&line);
    out.push('\n');
    out
}

fn leaves(values: &[Value]) -> Vec<i64> {
    values
        .iter()
        .flat_map(|v| v.leaves.iter().copied())
        .collect()
}

fn read_args(out: &mut String, tys: &[Ty], indent: &str) {
    for (i, ty) in tys.iter().enumerate() {
        out.push_str(&format!("{indent}let a{i} = {};\n", next_expr(ty)));
    }
}

fn function(spec: &Spec, layouts: &Layouts, f: &FunctionSpec, fc: &FunctionCases) -> Vec<Item> {
    let module = &spec.module;
    let upper = f.name.to_uppercase();
    let call = call_expr(f);
    let ret = layouts.cairo(&fc.ret);
    let mut items = Vec::new();

    if !fc.cases.is_empty() {
        let rows: Vec<(Vec<i64>, Vec<i64>)> = fc
            .cases
            .iter()
            .map(|c| (leaves(&c.args), c.expected.leaves.clone()))
            .collect();
        let mut data = wrap_comment(&format!(
            "{module}::{}: {} cases, tolerance {} ULP - {}",
            f.name,
            fc.cases.len(),
            f.tolerance,
            f.justification.trim()
        ));
        data.push_str(&table(&format!("{upper}_CASES"), &rows));
        items.push(Item {
            text: data,
            glued: true,
        });

        let mut out = format!("#[test]\nfn golden_{module}_{}() {{\n", f.name);
        out.push_str(&format!(
            "    let name: ByteArray = \"{module}::{}\";\n",
            f.name
        ));
        out.push_str(&format!("    let mut d = {upper}_CASES.span();\n"));
        out.push_str("    let mut case: usize = 0;\n    while !d.is_empty() {\n");
        read_args(&mut out, &fc.arg_tys, "        ");
        let tol = f.tolerance;
        let check_one = |var: &str, ty: &Ty| {
            let tol = if ty.has_fixed_leaf() {
                format!("{tol}, ")
            } else {
                String::new()
            };
            format!(
                "        check_{}({var}, ref d, {tol}@name, case);\n",
                ty.snake()
            )
        };
        if let Ty::Tuple(elems) = &fc.ret {
            let vars: Vec<String> = (0..elems.len()).map(|i| format!("r{i}")).collect();
            out.push_str(&format!(
                "        let ({}): {ret} = {call};\n",
                vars.join(", ")
            ));
            for (var, ty) in vars.iter().zip(elems) {
                out.push_str(&check_one(var, ty));
            }
        } else {
            out.push_str(&format!("        let actual: {ret} = {call};\n"));
            out.push_str(&check_one("actual", &fc.ret));
        }
        out.push_str("        case += 1;\n    }\n}");
        items.push(item(out));
    }

    for p in &fc.panics {
        let const_name = format!("{upper}_PANICS_{}", p.name.to_uppercase());
        let data = leaves(&p.args);
        if !data.is_empty() {
            let mut text = wrap_comment(&format!("{module}::{}: panics ({}).", f.name, p.name));
            text.push_str(&table(&const_name, &[(data.clone(), Vec::new())]));
            items.push(Item { text, glued: true });
        }
        let expected = if p.expected.len() <= 31 {
            format!("'{}'", p.expected)
        } else {
            format!("\"{}\"", p.expected)
        };
        let mut out = format!("#[test]\n#[should_panic(expected: {expected})]\n");
        out.push_str(&format!(
            "fn golden_{module}_{}_panics_{}() {{\n",
            f.name, p.name
        ));
        if !data.is_empty() {
            out.push_str(&format!("    let mut d = {const_name}.span();\n"));
            read_args(&mut out, &fc.arg_tys, "    ");
        }
        out.push_str(&format!("    let _: {ret} = {call};\n}}"));
        items.push(item(out));
    }
    items
}

#[cfg(test)]
mod tests {
    use super::*;
    use glam::DMat4;

    const SPEC: &str = r#"
module = "demo"
package = "glam"
imports = ["glam_core::mat4::Mat4Trait"]

[[function]]
name = "mul_vec4"
call = "{0}.mul_vec4({1})"
args = [{ type = "Mat4", constraint = "rotation" }, "Vec4"]
ret = "Vec4"
cases = 3
tolerance = 4
justification = "dim ULP."
edges = [[[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], [1, 2, 3, 4]]]

[[function.panics]]
name = "boom"
args = [[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [0, 0, 0, 0]]
expected = "Mat4: boom"

[[function]]
name = "off"
enabled = false
call = "{0}.off()"
args = ["Mat4"]
ret = "Fixed"
cases = 1
tolerance = 0
justification = "disabled entries need no oracle."
"#;

    fn registry() -> Registry {
        let mut r = Registry::default();
        r.add("mul_vec4", |a| a[0].dmat4() * a[1].dvec4());
        r
    }

    #[test]
    fn output_is_deterministic_and_well_formed() {
        let spec: Spec = toml::from_str(SPEC).unwrap();
        let registry = registry();
        let first = module(&spec, Some(&registry)).unwrap();
        let second = module(&spec, Some(&registry)).unwrap();
        assert_eq!(first, second);
        assert!(first.starts_with(STUB));
        assert!(first.ends_with("}\n") && !first.ends_with("\n\n"));
        assert!(first
            .lines()
            .all(|l| l.len() <= MAX_LINE && l.trim_end() == l));
        assert!(first.contains("use glam_core::mat4::{Mat4, Mat4Trait};\nuse glam_core::vec4::Vec4;\n"));
        // Tables are glued to the previous item, tests are separated by a blank line.
        assert!(first.contains(
            "}\n// demo::mul_vec4: 4 cases, tolerance 4 ULP - dim ULP.\n#[cairofmt::skip]\n"
        ));
        assert!(first.contains("const MUL_VEC4_CASES: [i64; 96] = ["));
        assert!(first.contains("        let actual: Vec4 = a0.mul_vec4(a1);\n"));
        assert!(first.contains("        check_vec4(actual, ref d, 4, @name, case);\n"));
        assert!(first.contains(
            "#[should_panic(expected: 'Mat4: boom')]\nfn golden_demo_mul_vec4_panics_boom() {"
        ));
        assert!(!first.contains("off"));
        // The identity edge case comes first: expected == the vector.
        let identity = DMat4::IDENTITY
            .to_cols_array()
            .map(|x| (x * 4294967296.0) as i64);
        assert!(first.contains(&format!("    {},", identity[0])));
    }

    #[test]
    fn use_lines_follow_the_formatter_order() {
        let spec: Spec = toml::from_str(
            r#"
module = "demo"
package = "fixed"
imports = ["fixed::FixedTrait", "fixed::wide::dot3", "fixed::wide::RecipTrait"]

[[function]]
name = "id"
call = "{0}"
args = ["Fixed"]
ret = "Fixed"
cases = 1
tolerance = 0
justification = "exact."
"#,
        )
        .unwrap();
        let mut registry = Registry::default();
        registry.add("id", |a| a[0].f());
        let text = module(&spec, Some(&registry)).unwrap();
        assert!(text
            .contains("use fixed::wide::{RecipTrait, dot3};\nuse fixed::{Fixed, FixedTrait};\n"));
    }

    #[test]
    fn disabled_module_is_the_bare_stub() {
        let mut spec: Spec = toml::from_str(SPEC).unwrap();
        spec.enabled = false;
        assert_eq!(module(&spec, None).unwrap(), STUB);
    }

    #[test]
    fn missing_oracle_and_type_mismatch_are_errors() {
        let spec: Spec = toml::from_str(SPEC).unwrap();
        assert!(module(&spec, Some(&Registry::default()))
            .unwrap_err()
            .contains("no oracle"));
        let mut wrong = Registry::default();
        wrong.add("mul_vec4", |a| a[1].dvec4().x);
        assert!(module(&spec, Some(&wrong))
            .unwrap_err()
            .contains("returned `Fixed`"));
    }
}
